// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ASIS

#include "../ui.h"

void ui_screen_ha_screen_init(void)
{
ui_screen_ha = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_ha, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_ha, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_ha, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_screen_home_none_lable = lv_label_create(ui_screen_ha);
lv_obj_set_width( ui_screen_home_none_lable, 316);
lv_obj_set_height( ui_screen_home_none_lable, 38);
lv_obj_set_x( ui_screen_home_none_lable, 82 );
lv_obj_set_y( ui_screen_home_none_lable, 58 );
lv_label_set_text(ui_screen_home_none_lable,"Home Assistant\n");
lv_obj_set_style_text_color(ui_screen_home_none_lable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_screen_home_none_lable, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_screen_home_none_lable, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_screen_home_none_lable, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sensor5_btn = lv_btn_create(ui_screen_ha);
lv_obj_set_width( ui_sensor5_btn, 214);
lv_obj_set_height( ui_sensor5_btn, 164);
lv_obj_set_x( ui_sensor5_btn, 22 );
lv_obj_set_y( ui_sensor5_btn, 96 );
lv_obj_add_flag( ui_sensor5_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_sensor5_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sensor5_btn, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sensor5_btn, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sensor5_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sensor5_logo = lv_img_create(ui_sensor5_btn);
lv_img_set_src(ui_sensor5_logo, &ui_img_ic_temp_png);
lv_obj_set_width( ui_sensor5_logo, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_sensor5_logo, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_sensor5_logo, 69 );
lv_obj_set_y( ui_sensor5_logo, 22 );
lv_obj_add_flag( ui_sensor5_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_sensor5_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sensor5_label = lv_label_create(ui_sensor5_btn);
lv_obj_set_width( ui_sensor5_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sensor5_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sensor5_label, 0 );
lv_obj_set_y( ui_sensor5_label, -5 );
lv_obj_set_align( ui_sensor5_label, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_sensor5_label,CONFIG_SENSOR5_UI_NAME);
lv_obj_set_style_text_color(ui_sensor5_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_sensor5_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_sensor5_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sensor5_data = lv_label_create(ui_sensor5_btn);
lv_obj_set_width( ui_sensor5_data, 100);
lv_obj_set_height( ui_sensor5_data, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sensor5_data, 14 );
lv_obj_set_y( ui_sensor5_data, 83 );
lv_label_set_text(ui_sensor5_data,"N/A");
lv_obj_set_style_text_color(ui_sensor5_data, lv_color_hex(0xECBF41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_sensor5_data, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_sensor5_data, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_sensor5_data, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sensor5_unit = lv_label_create(ui_sensor5_btn);
lv_obj_set_width( ui_sensor5_unit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sensor5_unit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sensor5_unit, 125 );
lv_obj_set_y( ui_sensor5_unit, 85 );
lv_label_set_text(ui_sensor5_unit,CONFIG_SENSOR5_UI_UNIT);
lv_obj_set_style_text_color(ui_sensor5_unit, lv_color_hex(0xECBF41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_sensor5_unit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_sensor5_unit, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sensor6_btn = lv_btn_create(ui_screen_ha);
lv_obj_set_width( ui_sensor6_btn, 214);
lv_obj_set_height( ui_sensor6_btn, 164);
lv_obj_set_x( ui_sensor6_btn, 244 );
lv_obj_set_y( ui_sensor6_btn, 96 );
lv_obj_add_flag( ui_sensor6_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_sensor6_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sensor6_btn, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sensor6_btn, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sensor6_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sensor6_logo = lv_img_create(ui_sensor6_btn);
lv_img_set_src(ui_sensor6_logo, &ui_img_ic_hum_png);
lv_obj_set_width( ui_sensor6_logo, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_sensor6_logo, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_sensor6_logo, 69 );
lv_obj_set_y( ui_sensor6_logo, 22 );
lv_obj_add_flag( ui_sensor6_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_sensor6_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sensor6_label = lv_label_create(ui_sensor6_btn);
lv_obj_set_width( ui_sensor6_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sensor6_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sensor6_label, 0 );
lv_obj_set_y( ui_sensor6_label, -5 );
lv_obj_set_align( ui_sensor6_label, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_sensor6_label, CONFIG_SENSOR6_UI_NAME);
lv_obj_set_style_text_color(ui_sensor6_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_sensor6_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_sensor6_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sensor6_data = lv_label_create(ui_sensor6_btn);
lv_obj_set_width( ui_sensor6_data, 100);
lv_obj_set_height( ui_sensor6_data, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sensor6_data, 13 );
lv_obj_set_y( ui_sensor6_data, 83 );
lv_label_set_text(ui_sensor6_data,"N/A");
lv_obj_set_style_text_color(ui_sensor6_data, lv_color_hex(0x52AAE5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_sensor6_data, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_sensor6_data, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_sensor6_data, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sensor6_unit = lv_label_create(ui_sensor6_btn);
lv_obj_set_width( ui_sensor6_unit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sensor6_unit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sensor6_unit, 125 );
lv_obj_set_y( ui_sensor6_unit, 83 );
lv_label_set_text(ui_sensor6_unit, CONFIG_SENSOR6_UI_UNIT);
lv_obj_set_style_text_color(ui_sensor6_unit, lv_color_hex(0x52AAE5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_sensor6_unit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_sensor6_unit, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_switch1 = lv_btn_create(ui_screen_ha);
lv_obj_set_width( ui_switch1, 214);
lv_obj_set_height( ui_switch1, 164);
lv_obj_set_x( ui_switch1, 22 );
lv_obj_set_y( ui_switch1, 268 );
lv_obj_add_flag( ui_switch1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_switch1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_switch1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_switch1, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_switch1, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch1, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_switch1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_add_flag(ui_switch1, LV_OBJ_FLAG_CHECKABLE);

ui_switch1_logo = lv_img_create(ui_switch1);
lv_img_set_src(ui_switch1_logo, &ui_img_ic_switch2_off_png);
lv_obj_set_width( ui_switch1_logo, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_switch1_logo, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_switch1_logo, 39 );
lv_obj_set_y( ui_switch1_logo, 10 );
lv_obj_add_flag( ui_switch1_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_switch1_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_switch1_label = lv_label_create(ui_switch1);
lv_obj_set_width( ui_switch1_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_switch1_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_switch1_label, 0 );
lv_obj_set_y( ui_switch1_label, -5 );
lv_obj_set_align( ui_switch1_label, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_switch1_label, CONFIG_SWITCH1_UI_NAME);
lv_obj_set_style_text_color(ui_switch1_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_switch1_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_switch1_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_switch2 = lv_btn_create(ui_screen_ha);
lv_obj_set_width( ui_switch2, 214);
lv_obj_set_height( ui_switch2, 78);
lv_obj_set_x( ui_switch2, 244 );
lv_obj_set_y( ui_switch2, 268 );
lv_obj_add_flag( ui_switch2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_switch2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_switch2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_switch2, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_switch2, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch2, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_switch2, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_add_flag(ui_switch2, LV_OBJ_FLAG_CHECKABLE);

ui_switch2_logo = lv_img_create(ui_switch2);
lv_img_set_src(ui_switch2_logo, &ui_img_ic_switch1_off_png);
lv_obj_set_x( ui_switch2_logo, 120 );
lv_obj_set_y( ui_switch2_logo, 2 );
lv_obj_add_flag( ui_switch2_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_switch2_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_switch2_label = lv_label_create(ui_switch2);
lv_obj_set_width( ui_switch2_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_switch2_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_switch2_label, 16 );
lv_obj_set_y( ui_switch2_label, 22 );
lv_label_set_text(ui_switch2_label, CONFIG_SWITCH2_UI_NAME);
lv_obj_set_style_text_color(ui_switch2_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_switch2_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_switch2_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_switch3 = lv_btn_create(ui_screen_ha);
lv_obj_set_width( ui_switch3, 214);
lv_obj_set_height( ui_switch3, 78);
lv_obj_set_x( ui_switch3, 243 );
lv_obj_set_y( ui_switch3, 351 );
lv_obj_add_flag( ui_switch3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_switch3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_switch3, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_switch3, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_switch3, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch3, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_switch3, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_add_flag(ui_switch3, LV_OBJ_FLAG_CHECKABLE);

ui_switch3_label = lv_label_create(ui_switch3);
lv_obj_set_width( ui_switch3_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_switch3_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_switch3_label, 16 );
lv_obj_set_y( ui_switch3_label, 22 );
lv_label_set_text(ui_switch3_label,CONFIG_SWITCH3_UI_NAME);
lv_obj_set_style_text_color(ui_switch3_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_switch3_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_switch3_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_switch3_switch = lv_switch_create(ui_switch3);
lv_obj_set_width( ui_switch3_switch, 80);
lv_obj_set_height( ui_switch3_switch, 30);
lv_obj_set_x( ui_switch3_switch, 104 );
lv_obj_set_y( ui_switch3_switch, 19 );

lv_obj_set_style_radius(ui_switch3_switch, 40, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch3_switch, lv_color_hex(0x4F4F4F), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch3_switch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_switch3_switch, LV_GRAD_DIR_NONE, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch3_switch, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_switch3_switch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_switch3_switch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch3_switch, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

}
