// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorawan

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenTime
void ui_ScreenTime_screen_init(void);
void ui_event_ScreenTime(lv_event_t * e);
lv_obj_t * ui_ScreenTime;
lv_obj_t * ui_ImgBackground1;
lv_obj_t * ui_PnlHour1;
lv_obj_t * ui_LblHour1;
lv_obj_t * ui_PnlMin1;
lv_obj_t * ui_LblMin1;
lv_obj_t * ui_Pnllocation1;
lv_obj_t * ui_LblCity1;
lv_obj_t * ui_ImgLocation1;
lv_obj_t * ui_PnlDate1;
lv_obj_t * ui_LblDate1;
lv_obj_t * ui_LblDotTime1;
lv_obj_t * ui_PnlSlide1;
void ui_event_BtnLoRa1(lv_event_t * e);
lv_obj_t * ui_BtnLoRa1;
lv_obj_t * ui_LblLoRaStatus1;
void ui_event_BtnWifi1(lv_event_t * e);
lv_obj_t * ui_BtnWifi1;
lv_obj_t * ui_LblWifiStatus1;


// SCREEN: ui_ScreenSensor
void ui_ScreenSensor_screen_init(void);
void ui_event_ScreenSensor(lv_event_t * e);
lv_obj_t * ui_ScreenSensor;
lv_obj_t * ui_LblTime1;
lv_obj_t * ui_PnlDots1;
lv_obj_t * ui_PnlDot11;
lv_obj_t * ui_PnlDot12;
lv_obj_t * ui_PnlDot13;
lv_obj_t * ui_PnlDot14;
void ui_event_BtnHumi(lv_event_t * e);
lv_obj_t * ui_BtnHumi;
lv_obj_t * ui_ImgHumi;
lv_obj_t * ui_LblTitleHumi;
lv_obj_t * ui_LblDataHumi;
lv_obj_t * ui_LblUnitHumi;
void ui_event_BtnCO2(lv_event_t * e);
lv_obj_t * ui_BtnCO2;
lv_obj_t * ui_ImgCO2;
lv_obj_t * ui_LblTitleCO2;
lv_obj_t * ui_LblDataCO2;
lv_obj_t * ui_LblUnitCO2;
void ui_event_BtnTVOC(lv_event_t * e);
lv_obj_t * ui_BtnTVOC;
lv_obj_t * ui_ImgTVOC;
lv_obj_t * ui_LblTitleTVOC;
lv_obj_t * ui_LblDataTVOC;
lv_obj_t * ui_LblUnitTVOC;
void ui_event_BtnTmp(lv_event_t * e);
lv_obj_t * ui_BtnTmp;
lv_obj_t * ui_ImgTmp;
lv_obj_t * ui_LblTitleTmp;
lv_obj_t * ui_LblDataTmp;
lv_obj_t * ui_LblUnitTmp;
void ui_event_BtnWifi2(lv_event_t * e);
lv_obj_t * ui_BtnWifi2;
lv_obj_t * ui_LblWifiStatus2;
void ui_event_BtnLoRa2(lv_event_t * e);
lv_obj_t * ui_BtnLoRa2;
lv_obj_t * ui_LblLoRaStatus2;


// SCREEN: ui_ScreenBulb
void ui_ScreenBulb_screen_init(void);
void ui_event_ScreenBulb(lv_event_t * e);
lv_obj_t * ui_ScreenBulb;
void ui_event_BtnBackSBulb(lv_event_t * e);
lv_obj_t * ui_BtnBackSBulb;
lv_obj_t * ui_LblTitleBulb;
lv_obj_t * ui_ImgBulb;
void ui_event_SwitchBulb(lv_event_t * e);
lv_obj_t * ui_SwitchBulb;
lv_obj_t * ui_PnlDots2;
lv_obj_t * ui_PnlDot1;
lv_obj_t * ui_PnlDot3;
lv_obj_t * ui_PnlDot2;
lv_obj_t * ui_PnlDot4;


// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
void ui_event_ScreenSetting(lv_event_t * e);
lv_obj_t * ui_ScreenSetting;
lv_obj_t * ui_LblTime2;
lv_obj_t * ui_ImgSetting1;
lv_obj_t * ui_LblTitleSetting;
void ui_event_BtnUsrLoraWAN1(lv_event_t * e);
lv_obj_t * ui_BtnUsrLoraWAN1;
lv_obj_t * ui_ImgLoraWAN1;
lv_obj_t * ui_LblTitleLoraWAN1;
void ui_event_BtnUsrWifi1(lv_event_t * e);
lv_obj_t * ui_BtnUsrWifi1;
lv_obj_t * ui_ImgWifi1;
lv_obj_t * ui_LblTitleWIFI1;
void ui_event_BtnDisplay1(lv_event_t * e);
lv_obj_t * ui_BtnDisplay1;
lv_obj_t * ui_ImgDisplay1;
lv_obj_t * ui_LblTitleDisplay1;
void ui_event_BtnDateTime1(lv_event_t * e);
lv_obj_t * ui_BtnDateTime1;
lv_obj_t * ui_ImgDateTime1;
lv_obj_t * ui_LblTitleDateTime1;
lv_obj_t * ui_PnlDots3;
lv_obj_t * ui_PnlDot5;
lv_obj_t * ui_PnlDot7;
lv_obj_t * ui_PnlDot8;
lv_obj_t * ui_PnlDot6;


// SCREEN: ui_ScreenCharts
void ui_ScreenCharts_screen_init(void);
lv_obj_t * ui_ScreenCharts;
void ui_event_BtnBackSHistory(lv_event_t * e);
lv_obj_t * ui_BtnBackSHistory;
lv_obj_t * ui_LblTitleHistory;
lv_obj_t * ui_PnlHistory;
void ui_event_TabView2(lv_event_t * e);
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TabPageDay;
lv_obj_t * ui_ChartDay;
lv_obj_t * ui_TabPageWeek;
lv_obj_t * ui_ChartWeek;


// SCREEN: ui_ScreenLoRaWAN
void ui_ScreenLoRaWAN_screen_init(void);
lv_obj_t * ui_ScreenLoRaWAN;
void ui_event_BtnBackSLoRaWAN(lv_event_t * e);
lv_obj_t * ui_BtnBackSLoRaWAN;
lv_obj_t * ui_LblTitleLoRaWAN;
void ui_event_BtnLoRaWANConfirm(lv_event_t * e);
lv_obj_t * ui_BtnLoRaWANConfirm;
lv_obj_t * ui_LblLoRaWANConfirm;
lv_obj_t * ui_PnlLoRaWAN;
lv_obj_t * ui_PnlClassDef;
lv_obj_t * ui_LblClass;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_SwClass;
lv_obj_t * ui_LblA;
lv_obj_t * ui_LblC;
lv_obj_t * ui_PnlFrequecy;
lv_obj_t * ui_LblFreq;
lv_obj_t * ui_DdFreq;
lv_obj_t * ui_PnlUplink;
lv_obj_t * ui_LblUplink;
lv_obj_t * ui_PnlNum;
void ui_event_BtnMinus(lv_event_t * e);
lv_obj_t * ui_BtnMinus;
lv_obj_t * ui_LblMinus;
void ui_event_NumInterval(lv_event_t * e);
lv_obj_t * ui_NumInterval;
void ui_event_BtnPlus(lv_event_t * e);
lv_obj_t * ui_BtnPlus;
lv_obj_t * ui_LblPlus;
lv_obj_t * ui_PnlActivation;
lv_obj_t * ui_LblActivate;
lv_obj_t * ui_PanelSW;
void ui_event_SwActivation(lv_event_t * e);
lv_obj_t * ui_SwActivation;
lv_obj_t * ui_LblOTAA;
lv_obj_t * ui_LblABP;
lv_obj_t * ui_PnlInfoABP;
lv_obj_t * ui_PnlDevEUI2;
lv_obj_t * ui_LblKeyDevEUI2;
lv_obj_t * ui_LblDataDevEUI2;
lv_obj_t * ui_PnlDevAddr;
lv_obj_t * ui_LblKeyDevAddr;
lv_obj_t * ui_LblDataDevAddr;
lv_obj_t * ui_PnlAppSKey;
lv_obj_t * ui_LblKeyAppSKey;
lv_obj_t * ui_LblDataAppSKey;
lv_obj_t * ui_PnlNwkSKey;
lv_obj_t * ui_LblKeyNwkSKey;
lv_obj_t * ui_LblDataNwkSKey;
lv_obj_t * ui_PnlInfoOTAA;
lv_obj_t * ui_PnlDevEUI1;
lv_obj_t * ui_LblKeyDevEUI1;
lv_obj_t * ui_LblDataDevEUI1;
lv_obj_t * ui_PnlKeyJoinEUI;
lv_obj_t * ui_LblKeyJoinEUI;
lv_obj_t * ui_LblDataKeyJoinEUI;
lv_obj_t * ui_PnlAppKey;
lv_obj_t * ui_LblKeyAppKey;
lv_obj_t * ui_LblDataAppkey;
void ui_event_KeyNumInterval(lv_event_t * e);
lv_obj_t * ui_KeyNumInterval;
void ui_event_toTerminal(lv_event_t * e);
lv_obj_t * ui_toTerminal;
lv_obj_t * ui_Label3;
void ui_event_BtnLoRaWANStatus(lv_event_t * e);
lv_obj_t * ui_BtnLoRaWANStatus;
lv_obj_t * ui_LblLoRaWANStatus;


// SCREEN: ui_ScreenWIFI
void ui_ScreenWIFI_screen_init(void);
lv_obj_t * ui_ScreenWIFI;
void ui_event_BtnBackSWifi(lv_event_t * e);
lv_obj_t * ui_BtnBackSWifi;
lv_obj_t * ui_LblTitleWifi;


// SCREEN: ui_ScreenDisplay
void ui_ScreenDisplay_screen_init(void);
void ui_event_ScreenDisplay(lv_event_t * e);
lv_obj_t * ui_ScreenDisplay;
lv_obj_t * ui_brighness1;
void ui_event_brighness_cfg1(lv_event_t * e);
lv_obj_t * ui_brighness_cfg1;
lv_obj_t * ui_brighness_title1;
lv_obj_t * ui_brighness_icon_3;
lv_obj_t * ui_brighness_icon_4;
lv_obj_t * ui_PnlSleepModeTime;
lv_obj_t * ui_after1;
void ui_event_sleep_mode_time_cfg1(lv_event_t * e);
lv_obj_t * ui_sleep_mode_time_cfg1;
lv_obj_t * ui_min2;
lv_obj_t * ui_sleep_mode1;
lv_obj_t * ui_sleep_mode_title1;
void ui_event_sleep_mode_cfg1(lv_event_t * e);
lv_obj_t * ui_sleep_mode_cfg1;
void ui_event_KeyDisplay1(lv_event_t * e);
lv_obj_t * ui_KeyDisplay1;
lv_obj_t * ui_LblTitleDisplay;
void ui_event_BtnBackSDisplay(lv_event_t * e);
lv_obj_t * ui_BtnBackSDisplay;


// SCREEN: ui_ScreenDatetime
void ui_ScreenDatetime_screen_init(void);
lv_obj_t * ui_ScreenDatetime;
lv_obj_t * ui_PnlManualSetting1;
lv_obj_t * ui_manual_setting_title2;
lv_obj_t * ui_PnlTimeContainer1;
lv_obj_t * ui_date_cfg2;
lv_obj_t * ui_PnlTimeSet1;
lv_obj_t * ui_hour_cfg1;
lv_obj_t * ui_time_label1;
lv_obj_t * ui_min_cfg1;
lv_obj_t * ui_time_label2;
lv_obj_t * ui_sec_cfg2;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_auto_update1;
lv_obj_t * ui_auto_update_title1;
void ui_event_auto_update_cfg1(lv_event_t * e);
lv_obj_t * ui_auto_update_cfg1;
lv_obj_t * ui_time_format1;
lv_obj_t * ui_time_format_title1;
lv_obj_t * ui_time_format_cfg1;
void ui_event_BtnBackSDateTime(lv_event_t * e);
lv_obj_t * ui_BtnBackSDateTime;
lv_obj_t * ui_LblTitleDateTime;


// SCREEN: ui_ScreenConsole
void ui_ScreenConsole_screen_init(void);
lv_obj_t * ui_ScreenConsole;
void ui_event_BtnBackSConsole(lv_event_t * e);
lv_obj_t * ui_BtnBackSConsole;
lv_obj_t * ui_LblTitleConsole;
lv_obj_t * ui_PnlConsole;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_co[1] = {&ui_img_co2_png};
const lv_img_dsc_t * ui_imgset_humidity_[2] = {&ui_img_humidity_1_png, &ui_img_humidity_2_png};
const lv_img_dsc_t * ui_imgset_location[1] = {&ui_img_location2_png};
const lv_img_dsc_t * ui_imgset_temp_[2] = {&ui_img_temp_1_png, &ui_img_temp_2_png};
const lv_img_dsc_t * ui_imgset_wifi_[3] = {&ui_img_wifi_1_png, &ui_img_wifi_2_png, &ui_img_wifi_3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSensor, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_ScreenSensor_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_ScreenSetting_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        fn_save_pre_screen(e);
    }
}
void ui_event_BtnLoRa1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLoRaWAN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, &ui_ScreenLoRaWAN_screen_init);
    }
}
void ui_event_BtnWifi1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWIFI, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0, &ui_ScreenWIFI_screen_init);
    }
}
void ui_event_ScreenSensor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenBulb, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_ScreenBulb_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenTime, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_ScreenTime_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        fn_save_pre_screen(e);
    }
}
void ui_event_BtnHumi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_clicked_sensor_charts_event(e);
    }
}
void ui_event_BtnCO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        btn_clicked_sensor_charts_event(e);
    }
}
void ui_event_BtnTVOC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        btn_clicked_sensor_charts_event(e);
    }
}
void ui_event_BtnTmp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_clicked_sensor_charts_event(e);
    }
}
void ui_event_BtnWifi2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWIFI, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0, &ui_ScreenWIFI_screen_init);
    }
}
void ui_event_BtnLoRa2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLoRaWAN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, &ui_ScreenLoRaWAN_screen_init);
    }
}
void ui_event_ScreenBulb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_ScreenSetting_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSensor, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_ScreenSensor_screen_init);
    }
}
void ui_event_BtnBackSBulb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLoRaWAN, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_ScreenLoRaWAN_screen_init);
    }
}
void ui_event_SwitchBulb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lora_light_off(e);
        _ui_image_set_property(ui_ImgBulb, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_bulb_dark_png);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lora_light_on(e);
        _ui_image_set_property(ui_ImgBulb, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_bulb_light_png);
    }
}
void ui_event_ScreenSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenTime, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_ScreenTime_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenBulb, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_ScreenBulb_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        fn_save_pre_screen(e);
    }
}
void ui_event_BtnUsrLoraWAN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_ScreenLoRaWAN, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenLoRaWAN_screen_init);
    }
}
void ui_event_BtnUsrWifi1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_ScreenWIFI, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenWIFI_screen_init);
    }
}
void ui_event_BtnDisplay1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_ScreenDisplay, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenDisplay_screen_init);
    }
}
void ui_event_BtnDateTime1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_ScreenDatetime, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenDatetime_screen_init);
    }
}
void ui_event_BtnBackSHistory(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSensor, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenSensor_screen_init);
    }
}
void ui_event_TabView2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TabviewChanged(e);
    }
}
void ui_event_BtnBackSLoRaWAN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Back2PreScreen(e);
    }
}
void ui_event_BtnLoRaWANConfirm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_ScreenDatetime, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenDatetime_screen_init);
    }
}
void ui_event_BtnMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnPlusDecreaseNum(e);
    }
}
void ui_event_NumInterval(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyNumInterval, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyNumInterval, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        NumIntervalDefocused(e);
    }
}
void ui_event_BtnPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnPlusIncreaseNum(e);
    }
}
void ui_event_SwActivation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_PnlInfoOTAA, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PnlInfoABP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_PnlInfoOTAA, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PnlInfoABP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_KeyNumInterval(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyNumInterval, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_NumInterval, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_toTerminal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenConsole, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenConsole_screen_init);
    }
}
void ui_event_BtnLoRaWANStatus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_BtnLoRaWANStatus, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        fn_LoRaWANStatus_clicked(e);
    }
}
void ui_event_BtnBackSWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Back2PreScreen(e);
    }
}
void ui_event_ScreenDisplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        brighness_update_callback(e);
    }
}
void ui_event_brighness_cfg1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        brighness_cfg_event_cb(e);
    }
}
void ui_event_sleep_mode_time_cfg1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyDisplay1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyDisplay1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        NumIntervalDefocused(e);
        display_cfg_apply_event_cb(e);
    }
}
void ui_event_sleep_mode_cfg1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_PnlSleepModeTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        display_cfg_apply_event_cb(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_PnlSleepModeTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_KeyDisplay1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        display_cfg_apply_event_cb(e);
    }
}
void ui_event_KeyDisplay1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyDisplay1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_sleep_mode_time_cfg1, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_BtnBackSDisplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Back2PreScreen(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        save_timesetting(e);
    }
}
void ui_event_auto_update_cfg1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_PnlManualSetting1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_PnlManualSetting1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_BtnBackSDateTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Back2PreScreen(e);
    }
}
void ui_event_BtnBackSConsole(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLoRaWAN, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenLoRaWAN_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenTime_screen_init();
    ui_ScreenSensor_screen_init();
    ui_ScreenBulb_screen_init();
    ui_ScreenSetting_screen_init();
    ui_ScreenCharts_screen_init();
    ui_ScreenLoRaWAN_screen_init();
    ui_ScreenWIFI_screen_init();
    ui_ScreenDisplay_screen_init();
    ui_ScreenDatetime_screen_init();
    ui_ScreenConsole_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenTime);
}
