// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorawan

#ifndef _INDICATOR_LORAWAN_UI_H
#define _INDICATOR_LORAWAN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_ScreenTime
void ui_ScreenTime_screen_init(void);
void ui_event_ScreenTime(lv_event_t * e);
extern lv_obj_t * ui_ScreenTime;
extern lv_obj_t * ui_ImgBackground1;
extern lv_obj_t * ui_PnlHour1;
extern lv_obj_t * ui_LblHour1;
extern lv_obj_t * ui_PnlMin1;
extern lv_obj_t * ui_LblMin1;
extern lv_obj_t * ui_Pnllocation1;
extern lv_obj_t * ui_LblCity1;
extern lv_obj_t * ui_ImgLocation1;
extern lv_obj_t * ui_PnlDate1;
extern lv_obj_t * ui_LblDate1;
extern lv_obj_t * ui_LblDotTime1;
extern lv_obj_t * ui_PnlSlide1;
void ui_event_BtnLoRa1(lv_event_t * e);
extern lv_obj_t * ui_BtnLoRa1;
extern lv_obj_t * ui_LblLoRaStatus1;
void ui_event_BtnWifi1(lv_event_t * e);
extern lv_obj_t * ui_BtnWifi1;
extern lv_obj_t * ui_LblWifiStatus1;
// SCREEN: ui_ScreenSensor
void ui_ScreenSensor_screen_init(void);
void ui_event_ScreenSensor(lv_event_t * e);
extern lv_obj_t * ui_ScreenSensor;
extern lv_obj_t * ui_LblTime1;
extern lv_obj_t * ui_PnlDots1;
extern lv_obj_t * ui_PnlDot11;
extern lv_obj_t * ui_PnlDot12;
extern lv_obj_t * ui_PnlDot13;
extern lv_obj_t * ui_PnlDot14;
void ui_event_BtnHumi(lv_event_t * e);
extern lv_obj_t * ui_BtnHumi;
extern lv_obj_t * ui_ImgHumi;
extern lv_obj_t * ui_LblTitleHumi;
extern lv_obj_t * ui_LblDataHumi;
extern lv_obj_t * ui_LblUnitHumi;
void ui_event_BtnCO2(lv_event_t * e);
extern lv_obj_t * ui_BtnCO2;
extern lv_obj_t * ui_ImgCO2;
extern lv_obj_t * ui_LblTitleCO2;
extern lv_obj_t * ui_LblDataCO2;
extern lv_obj_t * ui_LblUnitCO2;
void ui_event_BtnTVOC(lv_event_t * e);
extern lv_obj_t * ui_BtnTVOC;
extern lv_obj_t * ui_ImgTVOC;
extern lv_obj_t * ui_LblTitleTVOC;
extern lv_obj_t * ui_LblDataTVOC;
extern lv_obj_t * ui_LblUnitTVOC;
void ui_event_BtnTmp(lv_event_t * e);
extern lv_obj_t * ui_BtnTmp;
extern lv_obj_t * ui_ImgTmp;
extern lv_obj_t * ui_LblTitleTmp;
extern lv_obj_t * ui_LblDataTmp;
extern lv_obj_t * ui_LblUnitTmp;
void ui_event_BtnWifi2(lv_event_t * e);
extern lv_obj_t * ui_BtnWifi2;
extern lv_obj_t * ui_LblWifiStatus2;
void ui_event_BtnLoRa2(lv_event_t * e);
extern lv_obj_t * ui_BtnLoRa2;
extern lv_obj_t * ui_LblLoRaStatus2;
// SCREEN: ui_ScreenBulb
void ui_ScreenBulb_screen_init(void);
void ui_event_ScreenBulb(lv_event_t * e);
extern lv_obj_t * ui_ScreenBulb;
void ui_event_BtnBackSBulb(lv_event_t * e);
extern lv_obj_t * ui_BtnBackSBulb;
extern lv_obj_t * ui_LblTitleBulb;
extern lv_obj_t * ui_ImgBulb;
void ui_event_SwitchBulb(lv_event_t * e);
extern lv_obj_t * ui_SwitchBulb;
extern lv_obj_t * ui_PnlDots2;
extern lv_obj_t * ui_PnlDot1;
extern lv_obj_t * ui_PnlDot3;
extern lv_obj_t * ui_PnlDot2;
extern lv_obj_t * ui_PnlDot4;
extern lv_obj_t * ui_LblTime3;
// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
void ui_event_ScreenSetting(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetting;
extern lv_obj_t * ui_LblTime2;
extern lv_obj_t * ui_ImgSetting1;
extern lv_obj_t * ui_LblTitleSetting;
void ui_event_BtnUsrLoraWAN1(lv_event_t * e);
extern lv_obj_t * ui_BtnUsrLoraWAN1;
extern lv_obj_t * ui_ImgLoraWAN1;
extern lv_obj_t * ui_LblTitleLoraWAN1;
void ui_event_BtnUsrWifi1(lv_event_t * e);
extern lv_obj_t * ui_BtnUsrWifi1;
extern lv_obj_t * ui_ImgWifi1;
extern lv_obj_t * ui_LblTitleWIFI1;
void ui_event_BtnDisplay1(lv_event_t * e);
extern lv_obj_t * ui_BtnDisplay1;
extern lv_obj_t * ui_ImgDisplay1;
extern lv_obj_t * ui_LblTitleDisplay1;
void ui_event_BtnDateTime1(lv_event_t * e);
extern lv_obj_t * ui_BtnDateTime1;
extern lv_obj_t * ui_ImgDateTime1;
extern lv_obj_t * ui_LblTitleDateTime1;
extern lv_obj_t * ui_PnlDots3;
extern lv_obj_t * ui_PnlDot5;
extern lv_obj_t * ui_PnlDot7;
extern lv_obj_t * ui_PnlDot8;
extern lv_obj_t * ui_PnlDot6;
// SCREEN: ui_ScreenCharts
void ui_ScreenCharts_screen_init(void);
extern lv_obj_t * ui_ScreenCharts;
void ui_event_BtnBackSHistory(lv_event_t * e);
extern lv_obj_t * ui_BtnBackSHistory;
extern lv_obj_t * ui_LblTitleHistory;
extern lv_obj_t * ui_PnlHistory;
void ui_event_TabView2(lv_event_t * e);
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPageDay;
extern lv_obj_t * ui_ChartDay;
extern lv_obj_t * ui_TabPageWeek;
extern lv_obj_t * ui_ChartWeek;
// SCREEN: ui_ScreenLoRaWAN
void ui_ScreenLoRaWAN_screen_init(void);
extern lv_obj_t * ui_ScreenLoRaWAN;
void ui_event_BtnBackSLoRaWAN(lv_event_t * e);
extern lv_obj_t * ui_BtnBackSLoRaWAN;
extern lv_obj_t * ui_LblTitleLoRaWAN;
void ui_event_BtnLoRaWANConfirm(lv_event_t * e);
extern lv_obj_t * ui_BtnLoRaWANConfirm;
extern lv_obj_t * ui_LblLoRaWANConfirm;
extern lv_obj_t * ui_PnlLoRaWAN;
extern lv_obj_t * ui_PnlClassDef;
extern lv_obj_t * ui_LblClass;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_SwClass;
extern lv_obj_t * ui_LblA;
extern lv_obj_t * ui_LblC;
extern lv_obj_t * ui_PnlFrequecy;
extern lv_obj_t * ui_LblFreq;
extern lv_obj_t * ui_DdFreq;
extern lv_obj_t * ui_PnlUplink;
extern lv_obj_t * ui_LblUplink;
extern lv_obj_t * ui_PnlNum;
void ui_event_BtnMinus(lv_event_t * e);
extern lv_obj_t * ui_BtnMinus;
extern lv_obj_t * ui_LblMinus;
void ui_event_NumInterval(lv_event_t * e);
extern lv_obj_t * ui_NumInterval;
void ui_event_BtnPlus(lv_event_t * e);
extern lv_obj_t * ui_BtnPlus;
extern lv_obj_t * ui_LblPlus;
extern lv_obj_t * ui_PnlActivation;
extern lv_obj_t * ui_LblActivate;
extern lv_obj_t * ui_PanelSW;
void ui_event_SwActivation(lv_event_t * e);
extern lv_obj_t * ui_SwActivation;
extern lv_obj_t * ui_LblOTAA;
extern lv_obj_t * ui_LblABP;
extern lv_obj_t * ui_PnlInfoABP;
extern lv_obj_t * ui_PnlDevEUI2;
extern lv_obj_t * ui_LblKeyDevEUI2;
extern lv_obj_t * ui_LblDataDevEUI2;
extern lv_obj_t * ui_PnlDevAddr;
extern lv_obj_t * ui_LblKeyDevAddr;
extern lv_obj_t * ui_LblDataDevAddr;
extern lv_obj_t * ui_PnlAppSKey;
extern lv_obj_t * ui_LblKeyAppSKey;
extern lv_obj_t * ui_LblDataAppSKey;
extern lv_obj_t * ui_PnlNwkSKey;
extern lv_obj_t * ui_LblKeyNwkSKey;
extern lv_obj_t * ui_LblDataNwkSKey;
extern lv_obj_t * ui_PnlInfoOTAA;
extern lv_obj_t * ui_PnlDevEUI1;
extern lv_obj_t * ui_LblKeyDevEUI1;
extern lv_obj_t * ui_LblDataDevEUI1;
extern lv_obj_t * ui_PnlKeyJoinEUI;
extern lv_obj_t * ui_LblKeyJoinEUI;
extern lv_obj_t * ui_LblDataKeyJoinEUI;
extern lv_obj_t * ui_PnlAppKey;
extern lv_obj_t * ui_LblKeyAppKey;
extern lv_obj_t * ui_LblDataAppkey;
void ui_event_KeyNumInterval(lv_event_t * e);
extern lv_obj_t * ui_KeyNumInterval;
void ui_event_toTerminal(lv_event_t * e);
extern lv_obj_t * ui_toTerminal;
extern lv_obj_t * ui_Label3;
void ui_event_BtnLoRaWANStatus(lv_event_t * e);
extern lv_obj_t * ui_BtnLoRaWANStatus;
extern lv_obj_t * ui_LblLoRaWANStatus;
// SCREEN: ui_ScreenWIFI
void ui_ScreenWIFI_screen_init(void);
extern lv_obj_t * ui_ScreenWIFI;
void ui_event_BtnBackSWifi(lv_event_t * e);
extern lv_obj_t * ui_BtnBackSWifi;
extern lv_obj_t * ui_LblTitleWifi;
// SCREEN: ui_ScreenDisplay
void ui_ScreenDisplay_screen_init(void);
void ui_event_ScreenDisplay(lv_event_t * e);
extern lv_obj_t * ui_ScreenDisplay;
extern lv_obj_t * ui_brighness1;
void ui_event_brighness_cfg1(lv_event_t * e);
extern lv_obj_t * ui_brighness_cfg1;
extern lv_obj_t * ui_brighness_title1;
extern lv_obj_t * ui_brighness_icon_3;
extern lv_obj_t * ui_brighness_icon_4;
extern lv_obj_t * ui_PnlSleepModeTime;
extern lv_obj_t * ui_after1;
void ui_event_sleep_mode_time_cfg1(lv_event_t * e);
extern lv_obj_t * ui_sleep_mode_time_cfg1;
extern lv_obj_t * ui_min2;
extern lv_obj_t * ui_sleep_mode1;
extern lv_obj_t * ui_sleep_mode_title1;
void ui_event_sleep_mode_cfg1(lv_event_t * e);
extern lv_obj_t * ui_sleep_mode_cfg1;
void ui_event_KeyDisplay1(lv_event_t * e);
extern lv_obj_t * ui_KeyDisplay1;
extern lv_obj_t * ui_LblTitleDisplay;
void ui_event_BtnBackSDisplay(lv_event_t * e);
extern lv_obj_t * ui_BtnBackSDisplay;
// SCREEN: ui_ScreenDatetime
void ui_ScreenDatetime_screen_init(void);
extern lv_obj_t * ui_ScreenDatetime;
extern lv_obj_t * ui_PnlManualSetting1;
extern lv_obj_t * ui_manual_setting_title2;
extern lv_obj_t * ui_PnlTimeContainer1;
extern lv_obj_t * ui_date_cfg2;
extern lv_obj_t * ui_PnlTimeSet1;
extern lv_obj_t * ui_hour_cfg1;
extern lv_obj_t * ui_time_label1;
extern lv_obj_t * ui_min_cfg1;
extern lv_obj_t * ui_time_label2;
extern lv_obj_t * ui_sec_cfg2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_auto_update1;
extern lv_obj_t * ui_auto_update_title1;
void ui_event_auto_update_cfg1(lv_event_t * e);
extern lv_obj_t * ui_auto_update_cfg1;
extern lv_obj_t * ui_time_format1;
extern lv_obj_t * ui_time_format_title1;
extern lv_obj_t * ui_time_format_cfg1;
void ui_event_BtnBackSDateTime(lv_event_t * e);
extern lv_obj_t * ui_BtnBackSDateTime;
extern lv_obj_t * ui_LblTitleDateTime;
// SCREEN: ui_ScreenConsole
void ui_ScreenConsole_screen_init(void);
extern lv_obj_t * ui_ScreenConsole;
void ui_event_BtnBackSConsole(lv_event_t * e);
extern lv_obj_t * ui_BtnBackSConsole;
extern lv_obj_t * ui_LblTitleConsole;
extern lv_obj_t * ui_PnlConsole;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_background_png);    // assets\background.png
LV_IMG_DECLARE(ui_img_location2_png);    // assets\location2.png
LV_IMG_DECLARE(ui_img_lora_disconnect_png);    // assets\LoRa disconnect.png
LV_IMG_DECLARE(ui_img_wifi_disconet_png);    // assets\wifi_disconet.png
LV_IMG_DECLARE(ui_img_humidity_2_png);    // assets\humidity_2.png
LV_IMG_DECLARE(ui_img_co2_png);    // assets\co2.png
LV_IMG_DECLARE(ui_img_tvoc_png);    // assets\tvoc.png
LV_IMG_DECLARE(ui_img_temp_2_png);    // assets\temp_2.png
LV_IMG_DECLARE(ui_img_back_png);    // assets\back.png
LV_IMG_DECLARE(ui_img_bulb_dark_png);    // assets\bulb dark.png
LV_IMG_DECLARE(ui_img_bulb_light_png);    // assets\bulb light.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets\setting.png
LV_IMG_DECLARE(ui_img_datacloud_png);    // assets\datacloud.png
LV_IMG_DECLARE(ui_img_wifi_setting_png);    // assets\wifi_setting.png
LV_IMG_DECLARE(ui_img_display_png);    // assets\display.png
LV_IMG_DECLARE(ui_img_time_png);    // assets\time.png
LV_IMG_DECLARE(ui_img_high_light_png);    // assets\high_light.png
LV_IMG_DECLARE(ui_img_low_light_png);    // assets\low_light.png
LV_IMG_DECLARE(ui_img_humidity_1_png);    // assets\humidity_1.png
LV_IMG_DECLARE(ui_img_197404883);    // assets\loading-out.png
LV_IMG_DECLARE(ui_img_location_png);    // assets\location.png
LV_IMG_DECLARE(ui_img_lock_png);    // assets\lock.png
LV_IMG_DECLARE(ui_img_lora_connected_png);    // assets\LoRa connected.png
LV_IMG_DECLARE(ui_img_lora_ing_png);    // assets\LoRa ing.png
LV_IMG_DECLARE(ui_img_temp_1_png);    // assets\temp_1.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets\wifi_1.png
LV_IMG_DECLARE(ui_img_wifi_2_png);    // assets\wifi_2.png
LV_IMG_DECLARE(ui_img_wifi_3_png);    // assets\wifi_3.png

LV_FONT_DECLARE(ui_font_HeadTitle);
LV_FONT_DECLARE(ui_font_ItemTitle);
LV_FONT_DECLARE(ui_font_OnlyNumBig);
LV_FONT_DECLARE(ui_font_SensorDataFont);
LV_FONT_DECLARE(ui_font_SmallTitle);
LV_FONT_DECLARE(ui_font_WifiItem);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
