// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorawan

#include "../ui.h"

void ui_ScreenConsole_screen_init(void)
{
    ui_ScreenConsole = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenConsole, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnBackSConsole = lv_btn_create(ui_ScreenConsole);
    lv_obj_set_width(ui_BtnBackSConsole, 100);
    lv_obj_set_height(ui_BtnBackSConsole, 50);
    lv_obj_set_x(ui_BtnBackSConsole, 10);
    lv_obj_set_y(ui_BtnBackSConsole, 30);
    lv_obj_add_flag(ui_BtnBackSConsole, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBackSConsole, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBackSConsole, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBackSConsole, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnBackSConsole, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblTitleConsole = lv_label_create(ui_ScreenConsole);
    lv_obj_set_width(ui_LblTitleConsole, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleConsole, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleConsole, 1);
    lv_obj_set_y(ui_LblTitleConsole, 50);
    lv_obj_set_align(ui_LblTitleConsole, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LblTitleConsole, "Console");
    lv_obj_set_style_text_font(ui_LblTitleConsole, &ui_font_HeadTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlConsole = lv_obj_create(ui_ScreenConsole);
    lv_obj_set_width(ui_PnlConsole, 480);
    lv_obj_set_height(ui_PnlConsole, 380);
    lv_obj_set_x(ui_PnlConsole, 0);
    lv_obj_set_y(ui_PnlConsole, -1);
    lv_obj_set_align(ui_PnlConsole, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_PnlConsole, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlConsole, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlConsole, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlConsole, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_PnlConsole, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlConsole, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBackSConsole, ui_event_BtnBackSConsole, LV_EVENT_ALL, NULL);

}
