// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorawan

#include "../ui.h"

void ui_ScreenSetting_screen_init(void)
{
    ui_ScreenSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTime2 = lv_label_create(ui_ScreenSetting);
    lv_obj_set_width(ui_LblTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTime2, 30);
    lv_obj_set_y(ui_LblTime2, 20);
    lv_label_set_text(ui_LblTime2, "00:00");
    lv_obj_set_style_text_font(ui_LblTime2, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgSetting1 = lv_img_create(ui_ScreenSetting);
    lv_img_set_src(ui_ImgSetting1, &ui_img_setting_png);
    lv_obj_set_width(ui_ImgSetting1, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_ImgSetting1, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_ImgSetting1, 28);
    lv_obj_set_y(ui_ImgSetting1, 86);
    lv_obj_add_flag(ui_ImgSetting1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgSetting1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTitleSetting = lv_label_create(ui_ScreenSetting);
    lv_obj_set_width(ui_LblTitleSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleSetting, 58);
    lv_obj_set_y(ui_LblTitleSetting, 86);
    lv_label_set_text(ui_LblTitleSetting, "Setting");
    lv_obj_set_style_text_font(ui_LblTitleSetting, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnUsrLoraWAN1 = lv_btn_create(ui_ScreenSetting);
    lv_obj_set_width(ui_BtnUsrLoraWAN1, 140);
    lv_obj_set_height(ui_BtnUsrLoraWAN1, 140);
    lv_obj_set_x(ui_BtnUsrLoraWAN1, 95);
    lv_obj_set_y(ui_BtnUsrLoraWAN1, -25);
    lv_obj_set_align(ui_BtnUsrLoraWAN1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnUsrLoraWAN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnUsrLoraWAN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnUsrLoraWAN1, lv_color_hex(0x4EACE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnUsrLoraWAN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgLoraWAN1 = lv_img_create(ui_BtnUsrLoraWAN1);
    lv_img_set_src(ui_ImgLoraWAN1, &ui_img_datacloud_png);
    lv_obj_set_width(ui_ImgLoraWAN1, LV_SIZE_CONTENT);   /// 63
    lv_obj_set_height(ui_ImgLoraWAN1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_ImgLoraWAN1, 0);
    lv_obj_set_y(ui_ImgLoraWAN1, -20);
    lv_obj_set_align(ui_ImgLoraWAN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgLoraWAN1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgLoraWAN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgLoraWAN1, 150);

    ui_LblTitleLoraWAN1 = lv_label_create(ui_BtnUsrLoraWAN1);
    lv_obj_set_width(ui_LblTitleLoraWAN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleLoraWAN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleLoraWAN1, 0);
    lv_obj_set_y(ui_LblTitleLoraWAN1, 25);
    lv_obj_set_align(ui_LblTitleLoraWAN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblTitleLoraWAN1, "LoRaWAN");
    lv_obj_set_style_text_font(ui_LblTitleLoraWAN1, &ui_font_ItemTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnUsrWifi1 = lv_btn_create(ui_ScreenSetting);
    lv_obj_set_width(ui_BtnUsrWifi1, 140);
    lv_obj_set_height(ui_BtnUsrWifi1, 140);
    lv_obj_set_x(ui_BtnUsrWifi1, -95);
    lv_obj_set_y(ui_BtnUsrWifi1, -25);
    lv_obj_set_align(ui_BtnUsrWifi1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_BtnUsrWifi1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnUsrWifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnUsrWifi1, lv_color_hex(0x529D53), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnUsrWifi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgWifi1 = lv_img_create(ui_BtnUsrWifi1);
    lv_img_set_src(ui_ImgWifi1, &ui_img_wifi_setting_png);
    lv_obj_set_width(ui_ImgWifi1, LV_SIZE_CONTENT);   /// 63
    lv_obj_set_height(ui_ImgWifi1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_ImgWifi1, 0);
    lv_obj_set_y(ui_ImgWifi1, -20);
    lv_obj_set_align(ui_ImgWifi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWifi1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTitleWIFI1 = lv_label_create(ui_BtnUsrWifi1);
    lv_obj_set_width(ui_LblTitleWIFI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleWIFI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleWIFI1, 0);
    lv_obj_set_y(ui_LblTitleWIFI1, 25);
    lv_obj_set_align(ui_LblTitleWIFI1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblTitleWIFI1, "WiFi");
    lv_obj_set_style_text_font(ui_LblTitleWIFI1, &ui_font_ItemTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnDisplay1 = lv_btn_create(ui_ScreenSetting);
    lv_obj_set_width(ui_BtnDisplay1, 140);
    lv_obj_set_height(ui_BtnDisplay1, 140);
    lv_obj_set_x(ui_BtnDisplay1, 95);
    lv_obj_set_y(ui_BtnDisplay1, -50);
    lv_obj_set_align(ui_BtnDisplay1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BtnDisplay1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnDisplay1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnDisplay1, lv_color_hex(0xEEBF41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnDisplay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgDisplay1 = lv_img_create(ui_BtnDisplay1);
    lv_img_set_src(ui_ImgDisplay1, &ui_img_display_png);
    lv_obj_set_width(ui_ImgDisplay1, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_ImgDisplay1, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_ImgDisplay1, 0);
    lv_obj_set_y(ui_ImgDisplay1, -20);
    lv_obj_set_align(ui_ImgDisplay1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgDisplay1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgDisplay1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTitleDisplay1 = lv_label_create(ui_BtnDisplay1);
    lv_obj_set_width(ui_LblTitleDisplay1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleDisplay1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleDisplay1, 0);
    lv_obj_set_y(ui_LblTitleDisplay1, 25);
    lv_obj_set_align(ui_LblTitleDisplay1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblTitleDisplay1, "Display");
    lv_obj_set_style_text_font(ui_LblTitleDisplay1, &ui_font_ItemTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnDateTime1 = lv_btn_create(ui_ScreenSetting);
    lv_obj_set_width(ui_BtnDateTime1, 140);
    lv_obj_set_height(ui_BtnDateTime1, 140);
    lv_obj_set_x(ui_BtnDateTime1, -95);
    lv_obj_set_y(ui_BtnDateTime1, -50);
    lv_obj_set_align(ui_BtnDateTime1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnDateTime1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnDateTime1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnDateTime1, lv_color_hex(0x0B88FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnDateTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgDateTime1 = lv_img_create(ui_BtnDateTime1);
    lv_img_set_src(ui_ImgDateTime1, &ui_img_time_png);
    lv_obj_set_width(ui_ImgDateTime1, LV_SIZE_CONTENT);   /// 56
    lv_obj_set_height(ui_ImgDateTime1, LV_SIZE_CONTENT);    /// 56
    lv_obj_set_x(ui_ImgDateTime1, 0);
    lv_obj_set_y(ui_ImgDateTime1, -20);
    lv_obj_set_align(ui_ImgDateTime1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgDateTime1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgDateTime1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTitleDateTime1 = lv_label_create(ui_BtnDateTime1);
    lv_obj_set_width(ui_LblTitleDateTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleDateTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleDateTime1, 0);
    lv_obj_set_y(ui_LblTitleDateTime1, 25);
    lv_obj_set_align(ui_LblTitleDateTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblTitleDateTime1, "Date&Time");
    lv_obj_set_style_text_font(ui_LblTitleDateTime1, &ui_font_ItemTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDots3 = lv_obj_create(ui_ScreenSetting);
    lv_obj_set_width(ui_PnlDots3, 100);
    lv_obj_set_height(ui_PnlDots3, 20);
    lv_obj_set_x(ui_PnlDots3, 0);
    lv_obj_set_y(ui_PnlDots3, -20);
    lv_obj_set_align(ui_PnlDots3, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PnlDots3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlDots3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDots3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlDots3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDots3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDots3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDots3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDot5 = lv_obj_create(ui_PnlDots3);
    lv_obj_set_width(ui_PnlDot5, 7);
    lv_obj_set_height(ui_PnlDot5, 7);
    lv_obj_set_align(ui_PnlDot5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlDot7 = lv_obj_create(ui_PnlDots3);
    lv_obj_set_width(ui_PnlDot7, 7);
    lv_obj_set_height(ui_PnlDot7, 7);
    lv_obj_set_align(ui_PnlDot7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlDot8 = lv_obj_create(ui_PnlDots3);
    lv_obj_set_width(ui_PnlDot8, 7);
    lv_obj_set_height(ui_PnlDot8, 7);
    lv_obj_set_align(ui_PnlDot8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlDot6 = lv_obj_create(ui_PnlDots3);
    lv_obj_set_width(ui_PnlDot6, 7);
    lv_obj_set_height(ui_PnlDot6, 7);
    lv_obj_set_align(ui_PnlDot6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlDot6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDot6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDot6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDot6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnUsrLoraWAN1, ui_event_BtnUsrLoraWAN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnUsrWifi1, ui_event_BtnUsrWifi1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnDisplay1, ui_event_BtnDisplay1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnDateTime1, ui_event_BtnDateTime1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSetting, ui_event_ScreenSetting, LV_EVENT_ALL, NULL);

}
