// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorawan

#include "../ui.h"

void ui_ScreenBulb_screen_init(void)
{
    ui_ScreenBulb = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBulb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnBackSBulb = lv_btn_create(ui_ScreenBulb);
    lv_obj_set_width(ui_BtnBackSBulb, 100);
    lv_obj_set_height(ui_BtnBackSBulb, 50);
    lv_obj_set_x(ui_BtnBackSBulb, 10);
    lv_obj_set_y(ui_BtnBackSBulb, 30);
    lv_obj_add_flag(ui_BtnBackSBulb, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBackSBulb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBackSBulb, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBackSBulb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnBackSBulb, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblTitleBulb = lv_label_create(ui_ScreenBulb);
    lv_obj_set_width(ui_LblTitleBulb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleBulb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleBulb, 1);
    lv_obj_set_y(ui_LblTitleBulb, 50);
    lv_obj_set_align(ui_LblTitleBulb, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LblTitleBulb, "Bulb");
    lv_obj_set_style_text_font(ui_LblTitleBulb, &ui_font_HeadTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBulb = lv_img_create(ui_ScreenBulb);
    lv_img_set_src(ui_ImgBulb, &ui_img_bulb_dark_png);
    lv_obj_set_width(ui_ImgBulb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgBulb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgBulb, 0);
    lv_obj_set_y(ui_ImgBulb, 20);
    lv_obj_set_align(ui_ImgBulb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBulb, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBulb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgBulb, 320);

    ui_SwitchBulb = lv_switch_create(ui_ScreenBulb);
    lv_obj_set_width(ui_SwitchBulb, 50);
    lv_obj_set_height(ui_SwitchBulb, 25);
    lv_obj_set_x(ui_SwitchBulb, 0);
    lv_obj_set_y(ui_SwitchBulb, -90);
    lv_obj_set_align(ui_SwitchBulb, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SwitchBulb, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags

    lv_obj_set_style_bg_color(ui_SwitchBulb, lv_color_hex(0x5CB27F), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchBulb, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_PnlDots2 = lv_obj_create(ui_ScreenBulb);
    lv_obj_set_width(ui_PnlDots2, 100);
    lv_obj_set_height(ui_PnlDots2, 20);
    lv_obj_set_x(ui_PnlDots2, 0);
    lv_obj_set_y(ui_PnlDots2, -20);
    lv_obj_set_align(ui_PnlDots2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PnlDots2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlDots2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDots2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlDots2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDots2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDots2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDots2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDot1 = lv_obj_create(ui_PnlDots2);
    lv_obj_set_width(ui_PnlDot1, 7);
    lv_obj_set_height(ui_PnlDot1, 7);
    lv_obj_set_align(ui_PnlDot1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlDot3 = lv_obj_create(ui_PnlDots2);
    lv_obj_set_width(ui_PnlDot3, 7);
    lv_obj_set_height(ui_PnlDot3, 7);
    lv_obj_set_align(ui_PnlDot3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlDot2 = lv_obj_create(ui_PnlDots2);
    lv_obj_set_width(ui_PnlDot2, 7);
    lv_obj_set_height(ui_PnlDot2, 7);
    lv_obj_set_align(ui_PnlDot2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlDot2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDot2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDot4 = lv_obj_create(ui_PnlDots2);
    lv_obj_set_width(ui_PnlDot4, 7);
    lv_obj_set_height(ui_PnlDot4, 7);
    lv_obj_set_align(ui_PnlDot4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTime3 = lv_label_create(ui_ScreenBulb);
    lv_obj_set_width(ui_LblTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTime3, 30);
    lv_obj_set_y(ui_LblTime3, 20);
    lv_label_set_text(ui_LblTime3, "00:00");
    lv_obj_set_style_text_font(ui_LblTime3, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBackSBulb, ui_event_BtnBackSBulb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchBulb, ui_event_SwitchBulb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenBulb, ui_event_ScreenBulb, LV_EVENT_ALL, NULL);

}
