// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorawan

#include "../ui.h"

void ui_ScreenLoRaWAN_screen_init(void)
{
    ui_ScreenLoRaWAN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLoRaWAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnBackSLoRaWAN = lv_btn_create(ui_ScreenLoRaWAN);
    lv_obj_set_width(ui_BtnBackSLoRaWAN, 100);
    lv_obj_set_height(ui_BtnBackSLoRaWAN, 50);
    lv_obj_set_x(ui_BtnBackSLoRaWAN, 10);
    lv_obj_set_y(ui_BtnBackSLoRaWAN, 30);
    lv_obj_add_flag(ui_BtnBackSLoRaWAN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBackSLoRaWAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBackSLoRaWAN, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBackSLoRaWAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnBackSLoRaWAN, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblTitleLoRaWAN = lv_label_create(ui_ScreenLoRaWAN);
    lv_obj_set_width(ui_LblTitleLoRaWAN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleLoRaWAN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleLoRaWAN, 1);
    lv_obj_set_y(ui_LblTitleLoRaWAN, 50);
    lv_obj_set_align(ui_LblTitleLoRaWAN, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LblTitleLoRaWAN, "LoRaWAN");
    lv_obj_set_style_text_font(ui_LblTitleLoRaWAN, &ui_font_HeadTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnLoRaWANConfirm = lv_btn_create(ui_ScreenLoRaWAN);
    lv_obj_set_width(ui_BtnLoRaWANConfirm, 108);
    lv_obj_set_height(ui_BtnLoRaWANConfirm, 54);
    lv_obj_set_x(ui_BtnLoRaWANConfirm, -97);
    lv_obj_set_y(ui_BtnLoRaWANConfirm, -321);
    lv_obj_set_align(ui_BtnLoRaWANConfirm, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnLoRaWANConfirm, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLoRaWANConfirm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnLoRaWANConfirm, lv_color_hex(0x0B88FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnLoRaWANConfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblLoRaWANConfirm = lv_label_create(ui_BtnLoRaWANConfirm);
    lv_obj_set_width(ui_LblLoRaWANConfirm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblLoRaWANConfirm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblLoRaWANConfirm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblLoRaWANConfirm, "Comfirm");
    lv_obj_set_style_text_font(ui_LblLoRaWANConfirm, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlLoRaWAN = lv_obj_create(ui_ScreenLoRaWAN);
    lv_obj_set_width(ui_PnlLoRaWAN, 380);
    lv_obj_set_height(ui_PnlLoRaWAN, 360);
    lv_obj_set_x(ui_PnlLoRaWAN, 0);
    lv_obj_set_y(ui_PnlLoRaWAN, -45);
    lv_obj_set_align(ui_PnlLoRaWAN, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PnlLoRaWAN, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlLoRaWAN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlLoRaWAN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlLoRaWAN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlLoRaWAN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PnlLoRaWAN, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlLoRaWAN, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PnlClassDef = lv_obj_create(ui_PnlLoRaWAN);
    lv_obj_set_width(ui_PnlClassDef, 150);
    lv_obj_set_height(ui_PnlClassDef, 50);
    lv_obj_set_flex_flow(ui_PnlClassDef, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlClassDef, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlClassDef, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlClassDef, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlClassDef, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblClass = lv_label_create(ui_PnlClassDef);
    lv_obj_set_width(ui_LblClass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblClass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblClass, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblClass, "Class: ");

    ui_Panel9 = lv_obj_create(ui_PnlClassDef);
    lv_obj_set_width(ui_Panel9, 75);
    lv_obj_set_height(ui_Panel9, 25);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel9, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwClass = lv_switch_create(ui_Panel9);
    lv_obj_set_width(ui_SwClass, 60);
    lv_obj_set_height(ui_SwClass, 25);
    lv_obj_set_align(ui_SwClass, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_SwClass, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SwClass, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_state(ui_SwClass, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_SwClass, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_radius(ui_SwClass, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwClass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwClass, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SwClass, 2, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_SwClass, lv_color_hex(0x529D52), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwClass, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_SwClass, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwClass, lv_color_hex(0x5CB27F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwClass, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SwClass, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SwClass, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SwClass, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SwClass, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SwClass, 2, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_SwClass, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_SwClass, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_SwClass, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_SwClass, 0, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_LblA = lv_label_create(ui_SwClass);
    lv_obj_set_width(ui_LblA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblA, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblA, "A");
    lv_obj_clear_flag(ui_LblA, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags

    ui_LblC = lv_label_create(ui_SwClass);
    lv_obj_set_width(ui_LblC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblC, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LblC, "C");

    ui_PnlFrequecy = lv_obj_create(ui_PnlLoRaWAN);
    lv_obj_set_width(ui_PnlFrequecy, 220);
    lv_obj_set_height(ui_PnlFrequecy, 50);
    lv_obj_set_x(ui_PnlFrequecy, 0);
    lv_obj_set_y(ui_PnlFrequecy, 50);
    lv_obj_clear_flag(ui_PnlFrequecy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlFrequecy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlFrequecy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblFreq = lv_label_create(ui_PnlFrequecy);
    lv_obj_set_width(ui_LblFreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblFreq, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblFreq, "Frequency: ");

    ui_DdFreq = lv_dropdown_create(ui_PnlFrequecy);
    lv_dropdown_set_options(ui_DdFreq, "AS923\nAU915\nCN779\nEU433\nEU868\nKR920\nIN865\nUS915\nRU864");
    lv_obj_set_width(ui_DdFreq, 85);
    lv_obj_set_height(ui_DdFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DdFreq, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_DdFreq, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags


    lv_obj_set_style_radius(lv_dropdown_get_list(ui_DdFreq), 5,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_DdFreq), 5,  LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DdFreq), lv_color_hex(0x5AB27B),
                              LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DdFreq), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);

    ui_PnlUplink = lv_obj_create(ui_PnlLoRaWAN);
    lv_obj_set_width(ui_PnlUplink, 360);
    lv_obj_set_height(ui_PnlUplink, 50);
    lv_obj_set_x(ui_PnlUplink, 0);
    lv_obj_set_y(ui_PnlUplink, 100);
    lv_obj_clear_flag(ui_PnlUplink, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlUplink, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlUplink, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblUplink = lv_label_create(ui_PnlUplink);
    lv_obj_set_width(ui_LblUplink, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblUplink, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblUplink, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblUplink, "Uplink interval (min): ");

    ui_PnlNum = lv_obj_create(ui_PnlUplink);
    lv_obj_set_width(ui_PnlNum, 140);
    lv_obj_set_height(ui_PnlNum, 50);
    lv_obj_set_align(ui_PnlNum, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_PnlNum, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlNum, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PnlNum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PnlNum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_PnlNum, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PnlNum, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PnlNum, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PnlNum, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_BtnMinus = lv_btn_create(ui_PnlNum);
    lv_obj_set_width(ui_BtnMinus, 35);
    lv_obj_set_height(ui_BtnMinus, 40);
    lv_obj_set_x(ui_BtnMinus, -10);
    lv_obj_set_y(ui_BtnMinus, 0);
    lv_obj_set_align(ui_BtnMinus, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMinus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnMinus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnMinus, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMinus = lv_label_create(ui_BtnMinus);
    lv_obj_set_width(ui_LblMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblMinus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMinus, "-");

    ui_NumInterval = lv_textarea_create(ui_PnlNum);
    lv_obj_set_width(ui_NumInterval, 38);
    lv_obj_set_height(ui_NumInterval, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_align(ui_NumInterval, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_NumInterval, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_NumInterval, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_NumInterval, NULL);
    else lv_textarea_set_accepted_chars(ui_NumInterval, "1234567890");
    lv_textarea_set_max_length(ui_NumInterval, 4);
    lv_textarea_set_text(ui_NumInterval, "1");
    lv_textarea_set_placeholder_text(ui_NumInterval, "1");
    lv_textarea_set_one_line(ui_NumInterval, true);



    ui_BtnPlus = lv_btn_create(ui_PnlNum);
    lv_obj_set_width(ui_BtnPlus, 35);
    lv_obj_set_height(ui_BtnPlus, 40);
    lv_obj_set_x(ui_BtnPlus, 10);
    lv_obj_set_y(ui_BtnPlus, 0);
    lv_obj_set_align(ui_BtnPlus, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_BtnPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPlus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPlus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnPlus, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblPlus = lv_label_create(ui_BtnPlus);
    lv_obj_set_width(ui_LblPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblPlus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPlus, "+");

    ui_PnlActivation = lv_obj_create(ui_PnlLoRaWAN);
    lv_obj_set_width(ui_PnlActivation, 360);
    lv_obj_set_height(ui_PnlActivation, 50);
    lv_obj_set_x(ui_PnlActivation, 0);
    lv_obj_set_y(ui_PnlActivation, 150);
    lv_obj_add_flag(ui_PnlActivation, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_PnlActivation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlActivation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlActivation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblActivate = lv_label_create(ui_PnlActivation);
    lv_obj_set_width(ui_LblActivate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblActivate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblActivate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblActivate, "Activation: ");

    ui_PanelSW = lv_obj_create(ui_PnlActivation);
    lv_obj_set_width(ui_PanelSW, 150);
    lv_obj_set_height(ui_PanelSW, 23);
    lv_obj_set_align(ui_PanelSW, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelSW, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSW, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSW, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelSW, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelSW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSW, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSW, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSW, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwActivation = lv_switch_create(ui_PanelSW);
    lv_obj_set_width(ui_SwActivation, 150);
    lv_obj_set_height(ui_SwActivation, 25);
    lv_obj_set_align(ui_SwActivation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SwActivation, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SwActivation, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SwActivation, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_radius(ui_SwActivation, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwActivation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwActivation, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_SwActivation, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SwActivation, 2, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_SwActivation, lv_color_hex(0x529D52), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwActivation, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwActivation, lv_color_hex(0x5CB27F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwActivation, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SwActivation, 50, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SwActivation, 2, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_SwActivation, 50, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_SwActivation, 0, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_LblOTAA = lv_label_create(ui_SwActivation);
    lv_obj_set_width(ui_LblOTAA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblOTAA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblOTAA, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblOTAA, "OTAA");
    lv_obj_clear_flag(ui_LblOTAA, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_LblABP = lv_label_create(ui_SwActivation);
    lv_obj_set_width(ui_LblABP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblABP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblABP, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LblABP, "ABP");
    lv_obj_clear_flag(ui_LblABP, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_PnlInfoABP = lv_obj_create(ui_PnlLoRaWAN);
    lv_obj_set_width(ui_PnlInfoABP, 360);
    lv_obj_set_height(ui_PnlInfoABP, 120);
    lv_obj_set_x(ui_PnlInfoABP, 0);
    lv_obj_set_y(ui_PnlInfoABP, 200);
    lv_obj_set_flex_flow(ui_PnlInfoABP, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PnlInfoABP, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PnlInfoABP, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PnlInfoABP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlInfoABP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlInfoABP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDevEUI2 = lv_obj_create(ui_PnlInfoABP);
    lv_obj_set_width(ui_PnlDevEUI2, 320);
    lv_obj_set_height(ui_PnlDevEUI2, 40);
    lv_obj_set_flex_flow(ui_PnlDevEUI2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlDevEUI2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PnlDevEUI2, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PnlDevEUI2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDevEUI2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDevEUI2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDevEUI2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PnlDevEUI2, lv_color_hex(0x5CB27F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDevEUI2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LblKeyDevEUI2 = lv_label_create(ui_PnlDevEUI2);
    lv_obj_set_width(ui_LblKeyDevEUI2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyDevEUI2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblKeyDevEUI2, 5);
    lv_obj_set_y(ui_LblKeyDevEUI2, 0);
    lv_label_set_text(ui_LblKeyDevEUI2, "DevEUI:");

    ui_LblDataDevEUI2 = lv_label_create(ui_PnlDevEUI2);
    lv_obj_set_width(ui_LblDataDevEUI2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDataDevEUI2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataDevEUI2, 75);
    lv_obj_set_y(ui_LblDataDevEUI2, 0);
    lv_label_set_text(ui_LblDataDevEUI2, "xxxxxxx");

    ui_PnlDevAddr = lv_obj_create(ui_PnlInfoABP);
    lv_obj_set_width(ui_PnlDevAddr, 320);
    lv_obj_set_height(ui_PnlDevAddr, 40);
    lv_obj_set_flex_flow(ui_PnlDevAddr, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlDevAddr, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PnlDevAddr, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PnlDevAddr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDevAddr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDevAddr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDevAddr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PnlDevAddr, lv_color_hex(0x5CB27F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDevAddr, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LblKeyDevAddr = lv_label_create(ui_PnlDevAddr);
    lv_obj_set_width(ui_LblKeyDevAddr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyDevAddr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblKeyDevAddr, 5);
    lv_obj_set_y(ui_LblKeyDevAddr, 0);
    lv_label_set_text(ui_LblKeyDevAddr, "DevAddr:");

    ui_LblDataDevAddr = lv_label_create(ui_PnlDevAddr);
    lv_obj_set_width(ui_LblDataDevAddr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDataDevAddr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataDevAddr, 75);
    lv_obj_set_y(ui_LblDataDevAddr, 0);
    lv_label_set_text(ui_LblDataDevAddr, "xxxxxxx");

    ui_PnlAppSKey = lv_obj_create(ui_PnlInfoABP);
    lv_obj_set_width(ui_PnlAppSKey, 320);
    lv_obj_set_height(ui_PnlAppSKey, 40);
    lv_obj_set_align(ui_PnlAppSKey, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PnlAppSKey, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlAppSKey, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PnlAppSKey, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PnlAppSKey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlAppSKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlAppSKey, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlAppSKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PnlAppSKey, lv_color_hex(0x5CB27F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlAppSKey, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LblKeyAppSKey = lv_label_create(ui_PnlAppSKey);
    lv_obj_set_width(ui_LblKeyAppSKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyAppSKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblKeyAppSKey, 3);
    lv_obj_set_y(ui_LblKeyAppSKey, 0);
    lv_obj_set_align(ui_LblKeyAppSKey, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LblKeyAppSKey, "AppSKey:");

    ui_LblDataAppSKey = lv_label_create(ui_PnlAppSKey);
    lv_obj_set_width(ui_LblDataAppSKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDataAppSKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataAppSKey, 75);
    lv_obj_set_y(ui_LblDataAppSKey, 0);
    lv_obj_set_align(ui_LblDataAppSKey, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LblDataAppSKey, "xxxxxxx");

    ui_PnlNwkSKey = lv_obj_create(ui_PnlInfoABP);
    lv_obj_set_width(ui_PnlNwkSKey, 320);
    lv_obj_set_height(ui_PnlNwkSKey, 40);
    lv_obj_set_align(ui_PnlNwkSKey, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PnlNwkSKey, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlNwkSKey, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PnlNwkSKey, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PnlNwkSKey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlNwkSKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlNwkSKey, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlNwkSKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PnlNwkSKey, lv_color_hex(0x5CB27F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlNwkSKey, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LblKeyNwkSKey = lv_label_create(ui_PnlNwkSKey);
    lv_obj_set_width(ui_LblKeyNwkSKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyNwkSKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyNwkSKey, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblKeyNwkSKey, "NwkSKey:");

    ui_LblDataNwkSKey = lv_label_create(ui_PnlNwkSKey);
    lv_obj_set_width(ui_LblDataNwkSKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDataNwkSKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataNwkSKey, 75);
    lv_obj_set_y(ui_LblDataNwkSKey, 0);
    lv_obj_set_align(ui_LblDataNwkSKey, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblDataNwkSKey, "xxxxxxx");

    ui_PnlInfoOTAA = lv_obj_create(ui_PnlLoRaWAN);
    lv_obj_set_width(ui_PnlInfoOTAA, 360);
    lv_obj_set_height(ui_PnlInfoOTAA, 120);
    lv_obj_set_x(ui_PnlInfoOTAA, 0);
    lv_obj_set_y(ui_PnlInfoOTAA, 200);
    lv_obj_set_flex_flow(ui_PnlInfoOTAA, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PnlInfoOTAA, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PnlInfoOTAA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlInfoOTAA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDevEUI1 = lv_obj_create(ui_PnlInfoOTAA);
    lv_obj_set_width(ui_PnlDevEUI1, 320);
    lv_obj_set_height(ui_PnlDevEUI1, 40);
    lv_obj_set_flex_flow(ui_PnlDevEUI1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlDevEUI1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PnlDevEUI1, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PnlDevEUI1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDevEUI1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDevEUI1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDevEUI1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PnlDevEUI1, lv_color_hex(0x5CB27F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDevEUI1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LblKeyDevEUI1 = lv_label_create(ui_PnlDevEUI1);
    lv_obj_set_width(ui_LblKeyDevEUI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyDevEUI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblKeyDevEUI1, 5);
    lv_obj_set_y(ui_LblKeyDevEUI1, 0);
    lv_label_set_text(ui_LblKeyDevEUI1, "DevEUI:");

    ui_LblDataDevEUI1 = lv_label_create(ui_PnlDevEUI1);
    lv_obj_set_width(ui_LblDataDevEUI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDataDevEUI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataDevEUI1, 75);
    lv_obj_set_y(ui_LblDataDevEUI1, 0);
    lv_label_set_text(ui_LblDataDevEUI1, "xxxxxxx");

    ui_PnlKeyJoinEUI = lv_obj_create(ui_PnlInfoOTAA);
    lv_obj_set_width(ui_PnlKeyJoinEUI, 320);
    lv_obj_set_height(ui_PnlKeyJoinEUI, 40);
    lv_obj_set_align(ui_PnlKeyJoinEUI, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PnlKeyJoinEUI, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlKeyJoinEUI, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PnlKeyJoinEUI, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PnlKeyJoinEUI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlKeyJoinEUI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlKeyJoinEUI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlKeyJoinEUI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PnlKeyJoinEUI, lv_color_hex(0x5CB27F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlKeyJoinEUI, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LblKeyJoinEUI = lv_label_create(ui_PnlKeyJoinEUI);
    lv_obj_set_width(ui_LblKeyJoinEUI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyJoinEUI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblKeyJoinEUI, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblKeyJoinEUI, "JoinEUI:");

    ui_LblDataKeyJoinEUI = lv_label_create(ui_PnlKeyJoinEUI);
    lv_obj_set_width(ui_LblDataKeyJoinEUI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDataKeyJoinEUI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataKeyJoinEUI, 75);
    lv_obj_set_y(ui_LblDataKeyJoinEUI, 0);
    lv_obj_set_align(ui_LblDataKeyJoinEUI, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblDataKeyJoinEUI, "xxxxxxx");

    ui_PnlAppKey = lv_obj_create(ui_PnlInfoOTAA);
    lv_obj_set_width(ui_PnlAppKey, 320);
    lv_obj_set_height(ui_PnlAppKey, 40);
    lv_obj_set_x(ui_PnlAppKey, -315);
    lv_obj_set_y(ui_PnlAppKey, 27);
    lv_obj_set_align(ui_PnlAppKey, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PnlAppKey, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlAppKey, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PnlAppKey, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_scroll_dir(ui_PnlAppKey, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PnlAppKey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlAppKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlAppKey, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlAppKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PnlAppKey, lv_color_hex(0x5CB27F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlAppKey, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LblKeyAppKey = lv_label_create(ui_PnlAppKey);
    lv_obj_set_width(ui_LblKeyAppKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblKeyAppKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblKeyAppKey, 3);
    lv_obj_set_y(ui_LblKeyAppKey, 0);
    lv_obj_set_align(ui_LblKeyAppKey, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LblKeyAppKey, "AppKey:");

    ui_LblDataAppkey = lv_label_create(ui_PnlAppKey);
    lv_obj_set_width(ui_LblDataAppkey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDataAppkey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataAppkey, 75);
    lv_obj_set_y(ui_LblDataAppkey, 0);
    lv_obj_set_align(ui_LblDataAppkey, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LblDataAppkey, "xxxxxxx");

    ui_KeyNumInterval = lv_keyboard_create(ui_ScreenLoRaWAN);
    lv_keyboard_set_mode(ui_KeyNumInterval, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyNumInterval, 160);
    lv_obj_set_height(ui_KeyNumInterval, 100);
    lv_obj_set_x(ui_KeyNumInterval, 135);
    lv_obj_set_y(ui_KeyNumInterval, 80);
    lv_obj_set_align(ui_KeyNumInterval, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyNumInterval, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_toTerminal = lv_btn_create(ui_ScreenLoRaWAN);
    lv_obj_set_width(ui_toTerminal, 100);
    lv_obj_set_height(ui_toTerminal, 50);
    lv_obj_set_x(ui_toTerminal, -60);
    lv_obj_set_y(ui_toTerminal, -10);
    lv_obj_set_align(ui_toTerminal, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_state(ui_toTerminal, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_toTerminal, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_toTerminal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_toTerminal, lv_color_hex(0x5AB27B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_toTerminal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_toTerminal, lv_color_hex(0x6B6262), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_toTerminal, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_toTerminal);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Console");

    ui_BtnLoRaWANStatus = lv_btn_create(ui_ScreenLoRaWAN);
    lv_obj_set_width(ui_BtnLoRaWANStatus, 100);
    lv_obj_set_height(ui_BtnLoRaWANStatus, 50);
    lv_obj_set_x(ui_BtnLoRaWANStatus, 60);
    lv_obj_set_y(ui_BtnLoRaWANStatus, -10);
    lv_obj_set_align(ui_BtnLoRaWANStatus, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BtnLoRaWANStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLoRaWANStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnLoRaWANStatus, lv_color_hex(0x5AB27B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnLoRaWANStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnLoRaWANStatus, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BtnLoRaWANStatus, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LblLoRaWANStatus = lv_label_create(ui_BtnLoRaWANStatus);
    lv_obj_set_width(ui_LblLoRaWANStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblLoRaWANStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblLoRaWANStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblLoRaWANStatus, "Join");

    lv_obj_add_event_cb(ui_BtnBackSLoRaWAN, ui_event_BtnBackSLoRaWAN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLoRaWANConfirm, ui_event_BtnLoRaWANConfirm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMinus, ui_event_BtnMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NumInterval, ui_event_NumInterval, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPlus, ui_event_BtnPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwActivation, ui_event_SwActivation, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyNumInterval, ui_NumInterval);
    lv_obj_add_event_cb(ui_KeyNumInterval, ui_event_KeyNumInterval, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_toTerminal, ui_event_toTerminal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLoRaWANStatus, ui_event_BtnLoRaWANStatus, LV_EVENT_ALL, NULL);

}
