// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorawan

#include "../ui.h"

void ui_ScreenSensor_screen_init(void)
{
    ui_ScreenSensor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSensor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTime1 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LblTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTime1, 30);
    lv_obj_set_y(ui_LblTime1, 20);
    lv_label_set_text(ui_LblTime1, "00:00");
    lv_obj_set_style_text_font(ui_LblTime1, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDots1 = lv_obj_create(ui_ScreenSensor);
    lv_obj_set_width(ui_PnlDots1, 100);
    lv_obj_set_height(ui_PnlDots1, 20);
    lv_obj_set_x(ui_PnlDots1, 0);
    lv_obj_set_y(ui_PnlDots1, -20);
    lv_obj_set_align(ui_PnlDots1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PnlDots1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PnlDots1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDots1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlDots1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDots1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDots1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDots1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDot11 = lv_obj_create(ui_PnlDots1);
    lv_obj_set_width(ui_PnlDot11, 7);
    lv_obj_set_height(ui_PnlDot11, 7);
    lv_obj_set_align(ui_PnlDot11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlDot12 = lv_obj_create(ui_PnlDots1);
    lv_obj_set_width(ui_PnlDot12, 7);
    lv_obj_set_height(ui_PnlDot12, 7);
    lv_obj_set_align(ui_PnlDot12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlDot12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDot12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDot12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDot12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlDot13 = lv_obj_create(ui_PnlDots1);
    lv_obj_set_width(ui_PnlDot13, 7);
    lv_obj_set_height(ui_PnlDot13, 7);
    lv_obj_set_align(ui_PnlDot13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlDot14 = lv_obj_create(ui_PnlDots1);
    lv_obj_set_width(ui_PnlDot14, 7);
    lv_obj_set_height(ui_PnlDot14, 7);
    lv_obj_set_align(ui_PnlDot14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDot14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnHumi = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_BtnHumi, 140);
    lv_obj_set_height(ui_BtnHumi, 200);
    lv_obj_set_x(ui_BtnHumi, 148);
    lv_obj_set_y(ui_BtnHumi, 80);
    lv_obj_set_align(ui_BtnHumi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHumi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHumi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnHumi, lv_color_hex(0x4EACE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgHumi = lv_img_create(ui_BtnHumi);
    lv_img_set_src(ui_ImgHumi, &ui_img_humidity_2_png);
    lv_obj_set_width(ui_ImgHumi, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_ImgHumi, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_ImgHumi, -45);
    lv_obj_set_y(ui_ImgHumi, -70);
    lv_obj_set_align(ui_ImgHumi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHumi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHumi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTitleHumi = lv_label_create(ui_BtnHumi);
    lv_obj_set_width(ui_LblTitleHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleHumi, 15);
    lv_obj_set_y(ui_LblTitleHumi, -70);
    lv_obj_set_align(ui_LblTitleHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblTitleHumi, "Humidity");
    lv_obj_set_style_text_font(ui_LblTitleHumi, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblDataHumi = lv_label_create(ui_BtnHumi);
    lv_obj_set_width(ui_LblDataHumi, 80);
    lv_obj_set_height(ui_LblDataHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataHumi, -30);
    lv_obj_set_y(ui_LblDataHumi, 0);
    lv_obj_set_align(ui_LblDataHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblDataHumi, "--");
    lv_obj_set_style_text_align(ui_LblDataHumi, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblDataHumi, &ui_font_SensorDataFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblUnitHumi = lv_label_create(ui_BtnHumi);
    lv_obj_set_width(ui_LblUnitHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblUnitHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblUnitHumi, 25);
    lv_obj_set_y(ui_LblUnitHumi, 0);
    lv_obj_set_align(ui_LblUnitHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblUnitHumi, "%");
    lv_obj_set_style_text_font(ui_LblUnitHumi, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCO2 = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_BtnCO2, 436);
    lv_obj_set_height(ui_BtnCO2, 140);
    lv_obj_set_x(ui_BtnCO2, 0);
    lv_obj_set_y(ui_BtnCO2, -100);
    lv_obj_set_align(ui_BtnCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCO2, lv_color_hex(0x529D53), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgCO2 = lv_img_create(ui_BtnCO2);
    lv_img_set_src(ui_ImgCO2, &ui_img_co2_png);
    lv_obj_set_width(ui_ImgCO2, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_ImgCO2, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_ImgCO2, -184);
    lv_obj_set_y(ui_ImgCO2, -40);
    lv_obj_set_align(ui_ImgCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgCO2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTitleCO2 = lv_label_create(ui_BtnCO2);
    lv_obj_set_width(ui_LblTitleCO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleCO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleCO2, -134);
    lv_obj_set_y(ui_LblTitleCO2, -40);
    lv_obj_set_align(ui_LblTitleCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblTitleCO2, "CO2");
    lv_obj_set_style_text_font(ui_LblTitleCO2, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblDataCO2 = lv_label_create(ui_BtnCO2);
    lv_obj_set_width(ui_LblDataCO2, 200);
    lv_obj_set_height(ui_LblDataCO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataCO2, -90);
    lv_obj_set_y(ui_LblDataCO2, -1);
    lv_obj_set_align(ui_LblDataCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblDataCO2, "-- ");
    lv_obj_set_style_text_align(ui_LblDataCO2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblDataCO2, &ui_font_SensorDataFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblUnitCO2 = lv_label_create(ui_BtnCO2);
    lv_obj_set_width(ui_LblUnitCO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblUnitCO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblUnitCO2, 35);
    lv_obj_set_y(ui_LblUnitCO2, 0);
    lv_obj_set_align(ui_LblUnitCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblUnitCO2, "ppm");
    lv_obj_set_style_text_font(ui_LblUnitCO2, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnTVOC = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_BtnTVOC, 140);
    lv_obj_set_height(ui_BtnTVOC, 200);
    lv_obj_set_x(ui_BtnTVOC, -148);
    lv_obj_set_y(ui_BtnTVOC, 80);
    lv_obj_set_align(ui_BtnTVOC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnTVOC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnTVOC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnTVOC, lv_color_hex(0xE06D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnTVOC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTVOC = lv_img_create(ui_BtnTVOC);
    lv_img_set_src(ui_ImgTVOC, &ui_img_tvoc_png);
    lv_obj_set_width(ui_ImgTVOC, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_ImgTVOC, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_ImgTVOC, -40);
    lv_obj_set_y(ui_ImgTVOC, -70);
    lv_obj_set_align(ui_ImgTVOC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTVOC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTVOC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTitleTVOC = lv_label_create(ui_BtnTVOC);
    lv_obj_set_width(ui_LblTitleTVOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleTVOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleTVOC, 15);
    lv_obj_set_y(ui_LblTitleTVOC, -70);
    lv_obj_set_align(ui_LblTitleTVOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblTitleTVOC, "tVOC");
    lv_obj_set_style_text_font(ui_LblTitleTVOC, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblDataTVOC = lv_label_create(ui_BtnTVOC);
    lv_obj_set_width(ui_LblDataTVOC, 100);
    lv_obj_set_height(ui_LblDataTVOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataTVOC, -21);
    lv_obj_set_y(ui_LblDataTVOC, 0);
    lv_obj_set_align(ui_LblDataTVOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblDataTVOC, "-- ");
    lv_obj_set_style_text_align(ui_LblDataTVOC, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblDataTVOC, &ui_font_SensorDataFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblUnitTVOC = lv_label_create(ui_BtnTVOC);
    lv_obj_set_width(ui_LblUnitTVOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblUnitTVOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblUnitTVOC, 44);
    lv_obj_set_y(ui_LblUnitTVOC, 4);
    lv_obj_set_align(ui_LblUnitTVOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblUnitTVOC, "");
    lv_obj_set_style_text_font(ui_LblUnitTVOC, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnTmp = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_BtnTmp, 140);
    lv_obj_set_height(ui_BtnTmp, 200);
    lv_obj_set_x(ui_BtnTmp, 0);
    lv_obj_set_y(ui_BtnTmp, 80);
    lv_obj_set_align(ui_BtnTmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnTmp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnTmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnTmp, lv_color_hex(0xEEBF41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnTmp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTmp = lv_img_create(ui_BtnTmp);
    lv_img_set_src(ui_ImgTmp, &ui_img_temp_2_png);
    lv_obj_set_width(ui_ImgTmp, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_ImgTmp, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_ImgTmp, -40);
    lv_obj_set_y(ui_ImgTmp, -70);
    lv_obj_set_align(ui_ImgTmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTitleTmp = lv_label_create(ui_BtnTmp);
    lv_obj_set_width(ui_LblTitleTmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleTmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleTmp, 15);
    lv_obj_set_y(ui_LblTitleTmp, -70);
    lv_obj_set_align(ui_LblTitleTmp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblTitleTmp, "Temp");
    lv_obj_set_style_text_font(ui_LblTitleTmp, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblDataTmp = lv_label_create(ui_BtnTmp);
    lv_obj_set_width(ui_LblDataTmp, 80);
    lv_obj_set_height(ui_LblDataTmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDataTmp, -20);
    lv_obj_set_y(ui_LblDataTmp, 0);
    lv_obj_set_align(ui_LblDataTmp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblDataTmp, "--");
    lv_obj_set_style_text_align(ui_LblDataTmp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblDataTmp, &ui_font_SensorDataFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblUnitTmp = lv_label_create(ui_BtnTmp);
    lv_obj_set_width(ui_LblUnitTmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblUnitTmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblUnitTmp, 35);
    lv_obj_set_y(ui_LblUnitTmp, 0);
    lv_obj_set_align(ui_LblUnitTmp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblUnitTmp, "C");
    lv_obj_set_style_text_font(ui_LblUnitTmp, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnWifi2 = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_BtnWifi2, 60);
    lv_obj_set_height(ui_BtnWifi2, 50);
    lv_obj_set_x(ui_BtnWifi2, 415);
    lv_obj_set_y(ui_BtnWifi2, 0);
    lv_obj_add_flag(ui_BtnWifi2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnWifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnWifi2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnWifi2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblWifiStatus2 = lv_img_create(ui_BtnWifi2);
    lv_img_set_src(ui_LblWifiStatus2, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_LblWifiStatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblWifiStatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblWifiStatus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LblWifiStatus2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LblWifiStatus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnLoRa2 = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_BtnLoRa2, 100);
    lv_obj_set_height(ui_BtnLoRa2, 45);
    lv_obj_set_x(ui_BtnLoRa2, 310);
    lv_obj_set_y(ui_BtnLoRa2, 5);
    lv_obj_add_flag(ui_BtnLoRa2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLoRa2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnLoRa2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnLoRa2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblLoRaStatus2 = lv_img_create(ui_BtnLoRa2);
    lv_img_set_src(ui_LblLoRaStatus2, &ui_img_lora_disconnect_png);
    lv_obj_set_align(ui_LblLoRaStatus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LblLoRaStatus2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LblLoRaStatus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LblLoRaStatus2, 190);

    lv_obj_add_event_cb(ui_BtnHumi, ui_event_BtnHumi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCO2, ui_event_BtnCO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnTVOC, ui_event_BtnTVOC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnTmp, ui_event_BtnTmp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnWifi2, ui_event_BtnWifi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLoRa2, ui_event_BtnLoRa2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSensor, ui_event_ScreenSensor, LV_EVENT_ALL, NULL);

}
