// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorawan

#include "../ui.h"

void ui_ScreenDisplay_screen_init(void)
{
    ui_ScreenDisplay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brighness1 = lv_obj_create(ui_ScreenDisplay);
    lv_obj_set_width(ui_brighness1, 400);
    lv_obj_set_height(ui_brighness1, 100);
    lv_obj_set_x(ui_brighness1, 0);
    lv_obj_set_y(ui_brighness1, -80);
    lv_obj_set_align(ui_brighness1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_brighness1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brighness_cfg1 = lv_slider_create(ui_brighness1);
    lv_slider_set_range(ui_brighness_cfg1, 1, 99);
    lv_obj_set_width(ui_brighness_cfg1, 250);
    lv_obj_set_height(ui_brighness_cfg1, 10);
    lv_obj_set_x(ui_brighness_cfg1, 0);
    lv_obj_set_y(ui_brighness_cfg1, 10);
    lv_obj_set_align(ui_brighness_cfg1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_brighness_cfg1, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brighness_cfg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brighness_cfg1, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brighness_cfg1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brighness_cfg1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brighness_cfg1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_brighness_title1 = lv_label_create(ui_brighness1);
    lv_obj_set_width(ui_brighness_title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brighness_title1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_brighness_title1, "Brightness");

    ui_brighness_icon_3 = lv_img_create(ui_brighness1);
    lv_img_set_src(ui_brighness_icon_3, &ui_img_high_light_png);
    lv_obj_set_width(ui_brighness_icon_3, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_brighness_icon_3, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_brighness_icon_3, 0);
    lv_obj_set_y(ui_brighness_icon_3, 10);
    lv_obj_set_align(ui_brighness_icon_3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_brighness_icon_3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brighness_icon_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brighness_icon_4 = lv_img_create(ui_brighness1);
    lv_img_set_src(ui_brighness_icon_4, &ui_img_low_light_png);
    lv_obj_set_width(ui_brighness_icon_4, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_brighness_icon_4, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_brighness_icon_4, 0);
    lv_obj_set_y(ui_brighness_icon_4, 10);
    lv_obj_set_align(ui_brighness_icon_4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_brighness_icon_4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brighness_icon_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlSleepModeTime = lv_obj_create(ui_ScreenDisplay);
    lv_obj_set_width(ui_PnlSleepModeTime, 400);
    lv_obj_set_height(ui_PnlSleepModeTime, 50);
    lv_obj_set_x(ui_PnlSleepModeTime, -1);
    lv_obj_set_y(ui_PnlSleepModeTime, 70);
    lv_obj_set_align(ui_PnlSleepModeTime, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlSleepModeTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_after1 = lv_label_create(ui_PnlSleepModeTime);
    lv_obj_set_width(ui_after1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_after1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_after1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_after1, "Turn Off Screen After");

    ui_sleep_mode_time_cfg1 = lv_textarea_create(ui_PnlSleepModeTime);
    lv_obj_set_width(ui_sleep_mode_time_cfg1, 60);
    lv_obj_set_height(ui_sleep_mode_time_cfg1, 40);
    lv_obj_set_x(ui_sleep_mode_time_cfg1, -50);
    lv_obj_set_y(ui_sleep_mode_time_cfg1, 0);
    lv_obj_set_align(ui_sleep_mode_time_cfg1, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_max_length(ui_sleep_mode_time_cfg1, 128);
    lv_textarea_set_text(ui_sleep_mode_time_cfg1, "1");
    lv_textarea_set_placeholder_text(ui_sleep_mode_time_cfg1, "1");
    lv_obj_set_style_bg_color(ui_sleep_mode_time_cfg1, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleep_mode_time_cfg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_min2 = lv_label_create(ui_PnlSleepModeTime);
    lv_obj_set_width(ui_min2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_min2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_min2, "min");

    ui_sleep_mode1 = lv_obj_create(ui_ScreenDisplay);
    lv_obj_set_width(ui_sleep_mode1, 400);
    lv_obj_set_height(ui_sleep_mode1, 50);
    lv_obj_set_x(ui_sleep_mode1, 0);
    lv_obj_set_y(ui_sleep_mode1, 10);
    lv_obj_set_align(ui_sleep_mode1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sleep_mode1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sleep_mode_title1 = lv_label_create(ui_sleep_mode1);
    lv_obj_set_width(ui_sleep_mode_title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sleep_mode_title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sleep_mode_title1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_sleep_mode_title1, "Always On");

    ui_sleep_mode_cfg1 = lv_switch_create(ui_sleep_mode1);
    lv_obj_set_width(ui_sleep_mode_cfg1, 50);
    lv_obj_set_height(ui_sleep_mode_cfg1, 25);
    lv_obj_set_align(ui_sleep_mode_cfg1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_state(ui_sleep_mode_cfg1, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_sleep_mode_cfg1, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleep_mode_cfg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sleep_mode_cfg1, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_sleep_mode_cfg1, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_sleep_mode_cfg1, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sleep_mode_cfg1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_KeyDisplay1 = lv_keyboard_create(ui_ScreenDisplay);
    lv_keyboard_set_mode(ui_KeyDisplay1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyDisplay1, 200);
    lv_obj_set_height(ui_KeyDisplay1, 120);
    lv_obj_set_x(ui_KeyDisplay1, 8);
    lv_obj_set_y(ui_KeyDisplay1, 160);
    lv_obj_set_align(ui_KeyDisplay1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyDisplay1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_LblTitleDisplay = lv_label_create(ui_ScreenDisplay);
    lv_obj_set_width(ui_LblTitleDisplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleDisplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleDisplay, 1);
    lv_obj_set_y(ui_LblTitleDisplay, 50);
    lv_obj_set_align(ui_LblTitleDisplay, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LblTitleDisplay, "Display");
    lv_obj_set_style_text_font(ui_LblTitleDisplay, &ui_font_HeadTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBackSDisplay = lv_btn_create(ui_ScreenDisplay);
    lv_obj_set_width(ui_BtnBackSDisplay, 100);
    lv_obj_set_height(ui_BtnBackSDisplay, 50);
    lv_obj_set_x(ui_BtnBackSDisplay, 10);
    lv_obj_set_y(ui_BtnBackSDisplay, 30);
    lv_obj_add_flag(ui_BtnBackSDisplay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBackSDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBackSDisplay, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBackSDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnBackSDisplay, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_brighness_cfg1, ui_event_brighness_cfg1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sleep_mode_time_cfg1, ui_event_sleep_mode_time_cfg1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sleep_mode_cfg1, ui_event_sleep_mode_cfg1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyDisplay1, ui_sleep_mode_time_cfg1);
    lv_obj_add_event_cb(ui_KeyDisplay1, ui_event_KeyDisplay1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnBackSDisplay, ui_event_BtnBackSDisplay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenDisplay, ui_event_ScreenDisplay, LV_EVENT_ALL, NULL);

}
