// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorahub

#include "../ui.h"

void ui_ScreenDatetime_screen_init(void)
{
    ui_ScreenDatetime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenDatetime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlManualSetting1 = lv_obj_create(ui_ScreenDatetime);
    lv_obj_set_width(ui_PnlManualSetting1, 400);
    lv_obj_set_height(ui_PnlManualSetting1, 110);
    lv_obj_set_x(ui_PnlManualSetting1, 0);
    lv_obj_set_y(ui_PnlManualSetting1, 30);
    lv_obj_set_align(ui_PnlManualSetting1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PnlManualSetting1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PnlManualSetting1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_manual_setting_title2 = lv_label_create(ui_PnlManualSetting1);
    lv_obj_set_width(ui_manual_setting_title2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_manual_setting_title2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_manual_setting_title2, 0);
    lv_obj_set_y(ui_manual_setting_title2, -5);
    lv_label_set_text(ui_manual_setting_title2, "Manual Setting");

    ui_PnlTimeContainer1 = lv_obj_create(ui_PnlManualSetting1);
    lv_obj_set_width(ui_PnlTimeContainer1, 400);
    lv_obj_set_height(ui_PnlTimeContainer1, 65);
    lv_obj_set_x(ui_PnlTimeContainer1, 0);
    lv_obj_set_y(ui_PnlTimeContainer1, 15);
    lv_obj_set_align(ui_PnlTimeContainer1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PnlTimeContainer1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PnlTimeContainer1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlTimeContainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date_cfg2 = lv_textarea_create(ui_PnlTimeContainer1);
    lv_obj_set_width(ui_date_cfg2, 115);
    lv_obj_set_height(ui_date_cfg2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_date_cfg2, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_date_cfg2, 12);
    lv_textarea_set_placeholder_text(ui_date_cfg2, "01/01/2023");
    lv_textarea_set_one_line(ui_date_cfg2, true);
    lv_obj_set_scrollbar_mode(ui_date_cfg2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_date_cfg2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date_cfg2, &ui_font_SmallTitle, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_date_cfg2, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_date_cfg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_date_cfg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_date_cfg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_date_cfg2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_date_cfg2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_PnlTimeSet1 = lv_obj_create(ui_PnlTimeContainer1);
    lv_obj_set_width(ui_PnlTimeSet1, 200);
    lv_obj_set_height(ui_PnlTimeSet1, 80);
    lv_obj_set_x(ui_PnlTimeSet1, -50);
    lv_obj_set_y(ui_PnlTimeSet1, 0);
    lv_obj_set_align(ui_PnlTimeSet1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PnlTimeSet1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PnlTimeSet1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlTimeSet1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour_cfg1 = lv_roller_create(ui_PnlTimeSet1);
    lv_roller_set_options(ui_hour_cfg1,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_hour_cfg1, 100);
    lv_obj_set_width(ui_hour_cfg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_hour_cfg1, LV_ALIGN_LEFT_MID);

    lv_obj_set_style_bg_color(ui_hour_cfg1, lv_color_hex(0x529D52), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hour_cfg1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_time_label1 = lv_label_create(ui_PnlTimeSet1);
    lv_obj_set_width(ui_time_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_label1, -25);
    lv_obj_set_y(ui_time_label1, 0);
    lv_obj_set_align(ui_time_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time_label1, ":");

    ui_min_cfg1 = lv_roller_create(ui_PnlTimeSet1);
    lv_roller_set_options(ui_min_cfg1,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_min_cfg1, 100);
    lv_obj_set_width(ui_min_cfg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_min_cfg1, 5);
    lv_obj_set_y(ui_min_cfg1, 0);
    lv_obj_set_align(ui_min_cfg1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_min_cfg1, lv_color_hex(0x529D52), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_min_cfg1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_time_label2 = lv_label_create(ui_PnlTimeSet1);
    lv_obj_set_width(ui_time_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_label2, -45);
    lv_obj_set_y(ui_time_label2, 0);
    lv_obj_set_align(ui_time_label2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_time_label2, ":");

    ui_sec_cfg2 = lv_roller_create(ui_PnlTimeSet1);
    lv_roller_set_options(ui_sec_cfg2,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_sec_cfg2, 100);
    lv_obj_set_width(ui_sec_cfg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sec_cfg2, 10);
    lv_obj_set_y(ui_sec_cfg2, 0);
    lv_obj_set_align(ui_sec_cfg2, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_bg_color(ui_sec_cfg2, lv_color_hex(0x529D52), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sec_cfg2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_PnlTimeContainer1);
    lv_obj_set_width(ui_Button2, 45);
    lv_obj_set_height(ui_Button2, 40);
    lv_obj_set_align(ui_Button2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x529D52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Save");

    ui_auto_update1 = lv_obj_create(ui_ScreenDatetime);
    lv_obj_set_width(ui_auto_update1, 400);
    lv_obj_set_height(ui_auto_update1, 50);
    lv_obj_set_x(ui_auto_update1, 0);
    lv_obj_set_y(ui_auto_update1, -60);
    lv_obj_set_align(ui_auto_update1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_auto_update1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_auto_update_title1 = lv_label_create(ui_auto_update1);
    lv_obj_set_width(ui_auto_update_title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auto_update_title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_auto_update_title1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_auto_update_title1, "Time Auto Update");

    ui_auto_update_cfg1 = lv_switch_create(ui_auto_update1);
    lv_obj_set_width(ui_auto_update_cfg1, 50);
    lv_obj_set_height(ui_auto_update_cfg1, 25);
    lv_obj_set_align(ui_auto_update_cfg1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_state(ui_auto_update_cfg1, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_auto_update_cfg1, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_auto_update_cfg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_auto_update_cfg1, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_auto_update_cfg1, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_auto_update_cfg1, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_auto_update_cfg1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_time_format1 = lv_obj_create(ui_ScreenDatetime);
    lv_obj_set_width(ui_time_format1, 400);
    lv_obj_set_height(ui_time_format1, 50);
    lv_obj_set_x(ui_time_format1, 0);
    lv_obj_set_y(ui_time_format1, -120);
    lv_obj_set_align(ui_time_format1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_time_format1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time_format_title1 = lv_label_create(ui_time_format1);
    lv_obj_set_width(ui_time_format_title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_format_title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time_format_title1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time_format_title1, "Time Format");

    ui_time_format_cfg1 = lv_dropdown_create(ui_time_format1);
    lv_dropdown_set_options(ui_time_format_cfg1, "24H\n12H");
    lv_obj_set_width(ui_time_format_cfg1, 100);
    lv_obj_set_height(ui_time_format_cfg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time_format_cfg1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_time_format_cfg1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_time_format_cfg1, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_format_cfg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_BtnBackSDateTime = lv_btn_create(ui_ScreenDatetime);
    lv_obj_set_width(ui_BtnBackSDateTime, 100);
    lv_obj_set_height(ui_BtnBackSDateTime, 50);
    lv_obj_set_x(ui_BtnBackSDateTime, 10);
    lv_obj_set_y(ui_BtnBackSDateTime, 30);
    lv_obj_add_flag(ui_BtnBackSDateTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBackSDateTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBackSDateTime, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBackSDateTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnBackSDateTime, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblTitleDateTime = lv_label_create(ui_ScreenDatetime);
    lv_obj_set_width(ui_LblTitleDateTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleDateTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleDateTime, 0);
    lv_obj_set_y(ui_LblTitleDateTime, 50);
    lv_obj_set_align(ui_LblTitleDateTime, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LblTitleDateTime, "Date & Time");
    lv_obj_set_style_text_font(ui_LblTitleDateTime, &ui_font_HeadTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_auto_update_cfg1, ui_event_auto_update_cfg1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnBackSDateTime, ui_event_BtnBackSDateTime, LV_EVENT_ALL, NULL);

}
