// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorahub

#include "../ui.h"

void ui_ScreenCharts_screen_init(void)
{
    ui_ScreenCharts = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCharts, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnBackSHistory = lv_btn_create(ui_ScreenCharts);
    lv_obj_set_width(ui_BtnBackSHistory, 100);
    lv_obj_set_height(ui_BtnBackSHistory, 50);
    lv_obj_set_x(ui_BtnBackSHistory, 10);
    lv_obj_set_y(ui_BtnBackSHistory, 30);
    lv_obj_add_flag(ui_BtnBackSHistory, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBackSHistory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBackSHistory, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBackSHistory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnBackSHistory, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblTitleHistory = lv_label_create(ui_ScreenCharts);
    lv_obj_set_width(ui_LblTitleHistory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblTitleHistory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTitleHistory, 1);
    lv_obj_set_y(ui_LblTitleHistory, 50);
    lv_obj_set_align(ui_LblTitleHistory, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LblTitleHistory, "Title");
    lv_obj_set_style_text_font(ui_LblTitleHistory, &ui_font_HeadTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlHistory = lv_obj_create(ui_ScreenCharts);
    lv_obj_set_width(ui_PnlHistory, 480);
    lv_obj_set_height(ui_PnlHistory, 400);
    lv_obj_set_align(ui_PnlHistory, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PnlHistory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlHistory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlHistory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView2 = lv_tabview_create(ui_PnlHistory, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView2, 460);
    lv_obj_set_height(ui_TabView2, 380);
    lv_obj_set_x(ui_TabView2, -1);
    lv_obj_set_y(ui_TabView2, 0);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x65C367),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x65C367),
                              LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView2), 50,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x65C367),
                                  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_TabPageDay = lv_tabview_add_tab(ui_TabView2, "Day");
    lv_obj_clear_flag(ui_TabPageDay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_ChartDay = lv_chart_create(ui_TabPageDay);
    lv_obj_set_width(ui_ChartDay, 400);
    lv_obj_set_height(ui_ChartDay, 260);
    lv_obj_set_align(ui_ChartDay, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartDay, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_ChartDay, LV_CHART_AXIS_PRIMARY_Y, 100, 600);
    lv_chart_set_range(ui_ChartDay, LV_CHART_AXIS_SECONDARY_Y, 200, 2000);
    lv_chart_set_div_line_count(ui_ChartDay, 0, 7);
    lv_chart_set_zoom_x(ui_ChartDay, 255);
    lv_chart_set_zoom_y(ui_ChartDay, 255);
    lv_chart_set_axis_tick(ui_ChartDay, LV_CHART_AXIS_PRIMARY_X, 0, 0, 8, 1, true, 50);
    lv_chart_set_axis_tick(ui_ChartDay, LV_CHART_AXIS_PRIMARY_Y, 50, 5, 10, 2, false, 50);
    lv_chart_set_axis_tick(ui_ChartDay, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 10, 2, false, 25);
    lv_chart_series_t * ui_ChartDay_series_1 = lv_chart_add_series(ui_ChartDay, lv_color_hex(0x65C367),
                                                                   LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ChartDay_series_1_array[] = { 220, 700, 1200, 500, 250, 123, 244, 550, 900, 1000 };
    lv_chart_set_ext_y_array(ui_ChartDay, ui_ChartDay_series_1, ui_ChartDay_series_1_array);
    lv_obj_set_style_bg_color(ui_ChartDay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartDay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ChartDay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ChartDay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ChartDay, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartDay, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartDay, lv_color_hex(0x4040FF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartDay, 20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ChartDay, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartDay, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartDay, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartDay, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartDay, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChartDay, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_ChartDay, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartDay, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartDay, 0, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_TabPageWeek = lv_tabview_add_tab(ui_TabView2, "Week");

    ui_ChartWeek = lv_chart_create(ui_TabPageWeek);
    lv_obj_set_width(ui_ChartWeek, 400);
    lv_obj_set_height(ui_ChartWeek, 260);
    lv_obj_set_align(ui_ChartWeek, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartWeek, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartWeek, 7);
    lv_chart_set_div_line_count(ui_ChartWeek, 0, 7);
    lv_chart_set_zoom_x(ui_ChartWeek, 255);
    lv_chart_set_zoom_y(ui_ChartWeek, 255);
    lv_chart_set_axis_tick(ui_ChartWeek, LV_CHART_AXIS_PRIMARY_X, 0, 0, 7, 1, true, 50);
    lv_chart_set_axis_tick(ui_ChartWeek, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_ChartWeek, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_obj_set_style_bg_color(ui_ChartWeek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartWeek, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ChartWeek, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ChartWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_border_color(ui_ChartWeek, lv_color_hex(0x9F2121), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartWeek, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartWeek, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartWeek, 0, LV_PART_TICKS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBackSHistory, ui_event_BtnBackSHistory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabView2, ui_event_TabView2, LV_EVENT_ALL, NULL);

}
