// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorahub

#include "../ui.h"

void ui_ScreenTime_screen_init(void)
{
    ui_ScreenTime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgBackground1 = lv_img_create(ui_ScreenTime);
    lv_img_set_src(ui_ImgBackground1, &ui_img_background_png);
    lv_obj_set_width(ui_ImgBackground1, lv_pct(100));
    lv_obj_set_height(ui_ImgBackground1, lv_pct(100));
    lv_obj_set_align(ui_ImgBackground1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBackground1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBackground1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlHour1 = lv_obj_create(ui_ImgBackground1);
    lv_obj_set_width(ui_PnlHour1, 200);
    lv_obj_set_height(ui_PnlHour1, 170);
    lv_obj_set_x(ui_PnlHour1, -110);
    lv_obj_set_y(ui_PnlHour1, 0);
    lv_obj_set_align(ui_PnlHour1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlHour1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlHour1, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlHour1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblHour1 = lv_label_create(ui_PnlHour1);
    lv_obj_set_width(ui_LblHour1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblHour1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblHour1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblHour1, "00");
    lv_obj_set_style_text_font(ui_LblHour1, &ui_font_OnlyNumBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlMin1 = lv_obj_create(ui_ImgBackground1);
    lv_obj_set_width(ui_PnlMin1, 200);
    lv_obj_set_height(ui_PnlMin1, 170);
    lv_obj_set_x(ui_PnlMin1, 110);
    lv_obj_set_y(ui_PnlMin1, 0);
    lv_obj_set_align(ui_PnlMin1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlMin1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlMin1, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlMin1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMin1 = lv_label_create(ui_PnlMin1);
    lv_obj_set_width(ui_LblMin1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMin1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblMin1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMin1, "00");
    lv_obj_set_style_text_font(ui_LblMin1, &ui_font_OnlyNumBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pnllocation1 = lv_obj_create(ui_ImgBackground1);
    lv_obj_set_width(ui_Pnllocation1, 399);
    lv_obj_set_height(ui_Pnllocation1, 30);
    lv_obj_set_x(ui_Pnllocation1, 6);
    lv_obj_set_y(ui_Pnllocation1, 103);
    lv_obj_set_align(ui_Pnllocation1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Pnllocation1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pnllocation1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pnllocation1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Pnllocation1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pnllocation1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pnllocation1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCity1 = lv_label_create(ui_Pnllocation1);
    lv_obj_set_width(ui_LblCity1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCity1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblCity1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LblCity1, "Shen Zhen");
    lv_obj_add_flag(ui_LblCity1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_LblCity1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgLocation1 = lv_img_create(ui_ImgBackground1);
    lv_img_set_src(ui_ImgLocation1, &ui_img_location2_png);
    lv_obj_set_width(ui_ImgLocation1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgLocation1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgLocation1, 199);
    lv_obj_set_y(ui_ImgLocation1, 103);
    lv_obj_set_align(ui_ImgLocation1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgLocation1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgLocation1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PnlDate1 = lv_obj_create(ui_ImgBackground1);
    lv_obj_set_width(ui_PnlDate1, 235);
    lv_obj_set_height(ui_PnlDate1, 30);
    lv_obj_set_x(ui_PnlDate1, -103);
    lv_obj_set_y(ui_PnlDate1, -108);
    lv_obj_set_align(ui_PnlDate1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlDate1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlDate1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlDate1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PnlDate1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlDate1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlDate1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblDate1 = lv_label_create(ui_PnlDate1);
    lv_obj_set_width(ui_LblDate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblDate1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LblDate1, "Monday, 06 / 03 /  2023");
    lv_label_set_recolor(ui_LblDate1, "true");
    lv_obj_set_style_text_font(ui_LblDate1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblDotTime1 = lv_label_create(ui_ImgBackground1);
    lv_obj_set_width(ui_LblDotTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDotTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblDotTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblDotTime1, ":");
    lv_obj_set_style_text_font(ui_LblDotTime1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlSlide1 = lv_obj_create(ui_ImgBackground1);
    lv_obj_set_width(ui_PnlSlide1, 480);
    lv_obj_set_height(ui_PnlSlide1, 6);
    lv_obj_set_align(ui_PnlSlide1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlSlide1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlSlide1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlSlide1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PnlSlide1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PnlSlide1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PnlSlide1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnLoRa1 = lv_btn_create(ui_ScreenTime);
    lv_obj_set_width(ui_BtnLoRa1, 100);
    lv_obj_set_height(ui_BtnLoRa1, 45);
    lv_obj_set_x(ui_BtnLoRa1, 310);
    lv_obj_set_y(ui_BtnLoRa1, 5);
    lv_obj_add_flag(ui_BtnLoRa1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLoRa1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnLoRa1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnLoRa1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblLoRaStatus1 = lv_img_create(ui_BtnLoRa1);
    lv_img_set_src(ui_LblLoRaStatus1, &ui_img_lora_disconnect_png);
    lv_obj_set_align(ui_LblLoRaStatus1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LblLoRaStatus1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LblLoRaStatus1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LblLoRaStatus1, 190);

    ui_BtnWifi1 = lv_btn_create(ui_ScreenTime);
    lv_obj_set_width(ui_BtnWifi1, 60);
    lv_obj_set_height(ui_BtnWifi1, 50);
    lv_obj_set_x(ui_BtnWifi1, 415);
    lv_obj_set_y(ui_BtnWifi1, 0);
    lv_obj_add_flag(ui_BtnWifi1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnWifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnWifi1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnWifi1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblWifiStatus1 = lv_img_create(ui_BtnWifi1);
    lv_img_set_src(ui_LblWifiStatus1, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_LblWifiStatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblWifiStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblWifiStatus1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LblWifiStatus1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LblWifiStatus1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BtnLoRa1, ui_event_BtnLoRa1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnWifi1, ui_event_BtnWifi1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenTime, ui_event_ScreenTime, LV_EVENT_ALL, NULL);

}
