// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: vision_v2_wifi

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Logo1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Logo1, &ui_img_562603699);
    lv_obj_set_width(ui_Logo1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Logo1, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_Logo1, 0);
    lv_obj_set_y(ui_Logo1, 90);
    lv_obj_set_align(ui_Logo1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Logo1, 60);

    ui_Model_Name = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Model_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Model_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Model_Name, 0);
    lv_obj_set_y(ui_Model_Name, 45);
    lv_obj_set_align(ui_Model_Name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Model_Name, "Vision Face");
    lv_obj_set_style_text_font(ui_Model_Name, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vision_image_1 = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_vision_image_1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_vision_image_1, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_vision_image_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vision_image_1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vision_image_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
