// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"
#include "esp_log.h"

// 定义日志TAG
static const char *TAG = "ui_screen_openai_key";

// 在文件开头添加全局变量
static float g_temp_value = 0.7;  // 初始值
static int g_max_tokens = 2048;  // Max tokens初始值

//修改该UI screen用于设置大模型相关参数
void ui_screen_openai_key_screen_init(void)
{
ui_screen_openai_key = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_openai_key, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi_st_8 = lv_img_create(ui_screen_openai_key);
lv_img_set_src(ui_wifi_st_8, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_st_8, -20 );
lv_obj_set_y( ui_wifi_st_8, 20 );
lv_obj_set_align( ui_wifi_st_8, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_set_api_key_title1 = lv_label_create(ui_screen_openai_key);
lv_obj_set_width( ui_set_api_key_title1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_set_api_key_title1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_set_api_key_title1, 1 );
lv_obj_set_y( ui_set_api_key_title1, 50 );
lv_obj_set_align( ui_set_api_key_title1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_set_api_key_title1, "Settings");
lv_obj_set_style_text_font(ui_set_api_key_title1, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_api_key_back_btn = lv_btn_create(ui_screen_openai_key);
lv_obj_set_width( ui_api_key_back_btn, 100);
lv_obj_set_height( ui_api_key_back_btn, 50);
lv_obj_set_x( ui_api_key_back_btn, 10 );
lv_obj_set_y( ui_api_key_back_btn, 30 );
lv_obj_add_flag( ui_api_key_back_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_api_key_back_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_api_key_back_btn, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_api_key_back_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_api_key_back_btn, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );

// 创建滚动容器
// 修改滚动容器的设置
lv_obj_t *scroll_container = lv_obj_create(ui_screen_openai_key);
lv_obj_set_size(scroll_container, 440, 350);  // 设置容器大小，宽度略大于面板宽度
lv_obj_set_pos(scroll_container, 0, 100);     // 位置在标题下方
lv_obj_set_align(scroll_container, LV_ALIGN_TOP_MID);
lv_obj_set_style_bg_opa(scroll_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT); // 透明背景
lv_obj_set_style_border_width(scroll_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT); // 无边框
lv_obj_set_style_pad_all(scroll_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT); // 无内边距
lv_obj_set_style_pad_bottom(scroll_container, 25, LV_PART_MAIN | LV_STATE_DEFAULT); // 底部添加25像素间距
lv_obj_set_scroll_dir(scroll_container, LV_DIR_VER); // 只允许垂直滚动
lv_obj_set_style_radius(scroll_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT); // 无圆角
lv_obj_clear_flag(scroll_container, LV_OBJ_FLAG_SCROLL_ELASTIC); // 禁用弹性滚动
lv_obj_add_flag(scroll_container, LV_OBJ_FLAG_SCROLL_MOMENTUM); // 启用滚动惯性

// 创建一个容器作为温度设置栏
// 修改温度面板的y坐标（从-80改为-105）
lv_obj_t *temperature_panel = lv_obj_create(scroll_container);
lv_obj_set_width(temperature_panel, 400);
lv_obj_set_height(temperature_panel, 50);
lv_obj_set_x(temperature_panel, 0);
lv_obj_set_y(temperature_panel, -105);  // 上移25像素
lv_obj_set_align(temperature_panel, LV_ALIGN_CENTER);
lv_obj_clear_flag(temperature_panel, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
lv_obj_set_style_bg_color(temperature_panel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(temperature_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(temperature_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(temperature_panel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_all(temperature_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_y(temperature_panel, 10); // 从顶部开始放置
lv_obj_set_align(temperature_panel, LV_ALIGN_TOP_MID);

// 添加温度标题标签到温度设置栏
ui_temperature_label = lv_label_create(temperature_panel);
lv_obj_set_width(ui_temperature_label, LV_SIZE_CONTENT);
lv_obj_set_height(ui_temperature_label, LV_SIZE_CONTENT);
lv_obj_set_align(ui_temperature_label, LV_ALIGN_LEFT_MID);  // 左对齐
lv_label_set_text(ui_temperature_label, "Temperature");  // 修正拼写

// 添加开关按钮到温度设置栏
ui_temperature_switch = lv_switch_create(temperature_panel);
lv_obj_set_width(ui_temperature_switch, 50);
lv_obj_set_height(ui_temperature_switch, 25);
lv_obj_set_align(ui_temperature_switch, LV_ALIGN_RIGHT_MID);  // 右对齐
lv_obj_add_state(ui_temperature_switch, LV_STATE_CHECKED); // 默认开启
lv_obj_add_event_cb(ui_temperature_switch, ui_event_temperature_switch, LV_EVENT_VALUE_CHANGED, NULL);
// 设置开关样式，参照ui_screen_always_on_cfg
lv_obj_set_style_bg_color(ui_temperature_switch, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_temperature_switch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_temperature_switch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_PRESSED);
lv_obj_set_style_bg_opa(ui_temperature_switch, 255, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_temperature_switch, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED);
lv_obj_set_style_bg_opa(ui_temperature_switch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

// 创建滑条容器（初始显示），与温度设置栏样式一致
lv_obj_t *slider_panel = lv_obj_create(scroll_container);
lv_obj_set_width(slider_panel, 400);
lv_obj_set_height(slider_panel, 50);
lv_obj_set_x(slider_panel, 0);
lv_obj_set_y(slider_panel, -49);  // 从-45改为-49，与上面panel保持6像素间距
lv_obj_set_align(slider_panel, LV_ALIGN_CENTER);
lv_obj_set_style_bg_color(slider_panel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(slider_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(slider_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(slider_panel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_all(slider_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_clear_flag(slider_panel, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_y(slider_panel, 56); // 温度面板高度(50) + 间距(6)
lv_obj_set_align(slider_panel, LV_ALIGN_TOP_MID);

// 添加温度滑块到滑条容器
ui_temperature_slider = lv_slider_create(slider_panel);
lv_obj_set_width(ui_temperature_slider, 290);  // 减少10像素
lv_obj_set_height(ui_temperature_slider, 15);
lv_obj_set_x(ui_temperature_slider, 10);  // 右移10像素
lv_obj_set_align(ui_temperature_slider, LV_ALIGN_LEFT_MID);
lv_slider_set_range(ui_temperature_slider, 0, 20);  // 范围0-2.0，步长为0.1
lv_slider_set_value(ui_temperature_slider, 7, LV_ANIM_OFF);  // 默认值0.7
// 添加多个事件回调，确保能捕获所有值变化
lv_obj_add_event_cb(ui_temperature_slider, ui_event_temperature_slider, LV_EVENT_VALUE_CHANGED, NULL);
lv_obj_add_event_cb(ui_temperature_slider, ui_event_temperature_slider, LV_EVENT_RELEASED, NULL);
// 设置滑块样式，参照ui_brighness_cfg
lv_obj_set_style_bg_color(ui_temperature_slider, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_temperature_slider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_temperature_slider, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_temperature_slider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_temperature_slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_temperature_slider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

// 添加温度值显示标签到滑条容器
ui_temperature_value = lv_label_create(slider_panel);
lv_obj_set_width(ui_temperature_value, 50);  // 固定宽度
lv_obj_set_height(ui_temperature_value, LV_SIZE_CONTENT);
lv_obj_set_align(ui_temperature_value, LV_ALIGN_RIGHT_MID);
lv_label_set_text_fmt(ui_temperature_value, "%.1f", g_temp_value);
lv_obj_set_style_text_font(ui_temperature_value, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_temperature_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

// 在temperature相关组件之后添加max tokens设置栏
lv_obj_t *max_tokens_panel = lv_obj_create(scroll_container);
lv_obj_set_width(max_tokens_panel, 400);  // 与temperature_panel宽度一致
lv_obj_set_height(max_tokens_panel, 50);  // 与temperature_panel高度一致
lv_obj_set_x(max_tokens_panel, 0);
lv_obj_set_y(max_tokens_panel, 7);  // 与slider_panel保持6像素间距
lv_obj_set_align(max_tokens_panel, LV_ALIGN_CENTER);
lv_obj_clear_flag(max_tokens_panel, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_bg_color(max_tokens_panel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(max_tokens_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(max_tokens_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(max_tokens_panel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_all(max_tokens_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_y(max_tokens_panel, 112); // 上一个面板底部位置(56+50) + 间距(6)
lv_obj_set_align(max_tokens_panel, LV_ALIGN_TOP_MID);

// 添加Max tokens标题标签
ui_max_tokens_label = lv_label_create(max_tokens_panel);
lv_obj_set_width(ui_max_tokens_label, LV_SIZE_CONTENT);
lv_obj_set_height(ui_max_tokens_label, LV_SIZE_CONTENT);
lv_obj_set_align(ui_max_tokens_label, LV_ALIGN_LEFT_MID);
lv_label_set_text(ui_max_tokens_label, "Max tokens");

// 添加Max tokens开关按钮
ui_max_tokens_switch = lv_switch_create(max_tokens_panel);
lv_obj_set_width(ui_max_tokens_switch, 50);
lv_obj_set_height(ui_max_tokens_switch, 25);
lv_obj_set_align(ui_max_tokens_switch, LV_ALIGN_RIGHT_MID);
lv_obj_add_state(ui_max_tokens_switch, LV_STATE_CHECKED);
lv_obj_add_event_cb(ui_max_tokens_switch, ui_event_max_tokens_switch, LV_EVENT_VALUE_CHANGED, NULL);
// 设置开关样式
lv_obj_set_style_bg_color(ui_max_tokens_switch, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_max_tokens_switch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_max_tokens_switch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_PRESSED);
lv_obj_set_style_bg_opa(ui_max_tokens_switch, 255, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_max_tokens_switch, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED);
lv_obj_set_style_bg_opa(ui_max_tokens_switch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

// 创建Max tokens滑条容器
lv_obj_t *max_tokens_slider_panel = lv_obj_create(scroll_container);
lv_obj_set_width(max_tokens_slider_panel, 400);
lv_obj_set_height(max_tokens_slider_panel, 50);
lv_obj_set_x(max_tokens_slider_panel, 0);
lv_obj_set_y(max_tokens_slider_panel, 63);  // 与max_tokens_panel保持6像素间距
lv_obj_set_align(max_tokens_slider_panel, LV_ALIGN_CENTER);
lv_obj_set_style_bg_color(max_tokens_slider_panel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(max_tokens_slider_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(max_tokens_slider_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(max_tokens_slider_panel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_all(max_tokens_slider_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_clear_flag(max_tokens_slider_panel, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_y(max_tokens_slider_panel, 168); // 上一个面板底部位置(112+50) + 间距(6)
lv_obj_set_align(max_tokens_slider_panel, LV_ALIGN_TOP_MID);

// 添加Max tokens滑块
ui_max_tokens_slider = lv_slider_create(max_tokens_slider_panel);
lv_obj_set_width(ui_max_tokens_slider, 290);
lv_obj_set_height(ui_max_tokens_slider, 15);
lv_obj_set_x(ui_max_tokens_slider, 10);  // 右移10像素，与temperature_slider对齐
lv_obj_set_align(ui_max_tokens_slider, LV_ALIGN_LEFT_MID);
lv_slider_set_range(ui_max_tokens_slider, 0, 4096);  // 范围0-4096
lv_slider_set_value(ui_max_tokens_slider, 2048, LV_ANIM_OFF);  // 默认值2048
lv_obj_add_event_cb(ui_max_tokens_slider, ui_event_max_tokens_slider, LV_EVENT_VALUE_CHANGED, NULL);
// 设置滑块样式
lv_obj_set_style_bg_color(ui_max_tokens_slider, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_max_tokens_slider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_max_tokens_slider, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_max_tokens_slider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_max_tokens_slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_max_tokens_slider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

// 添加Max tokens值显示标签
ui_max_tokens_value = lv_label_create(max_tokens_slider_panel);
lv_obj_set_width(ui_max_tokens_value, 50);
lv_obj_set_height(ui_max_tokens_value, LV_SIZE_CONTENT);
lv_obj_set_align(ui_max_tokens_value, LV_ALIGN_RIGHT_MID);
lv_label_set_text_fmt(ui_max_tokens_value, "%d", g_max_tokens);
lv_obj_set_style_text_font(ui_max_tokens_value, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_max_tokens_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

// 创建API Key状态容器
lv_obj_t *api_key_status_panel = lv_obj_create(scroll_container);
ui_api_key_status_panel = api_key_status_panel;
lv_obj_set_width(api_key_status_panel, 400);
lv_obj_set_height(api_key_status_panel, 50);
lv_obj_set_x(api_key_status_panel, 0);
lv_obj_set_y(api_key_status_panel, 119);  // 与上一个面板保持6像素间距
lv_obj_set_align(api_key_status_panel, LV_ALIGN_CENTER);
lv_obj_clear_flag(api_key_status_panel, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_bg_color(api_key_status_panel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(api_key_status_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(api_key_status_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(api_key_status_panel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_all(api_key_status_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_y(api_key_status_panel, 224); // 上一个面板底部位置(168+50) + 间距(6)
lv_obj_set_align(api_key_status_panel, LV_ALIGN_TOP_MID);

// 添加API Key状态标签
ui_api_key_status_label = lv_label_create(api_key_status_panel);
lv_obj_set_width(ui_api_key_status_label, LV_SIZE_CONTENT);
lv_obj_set_height(ui_api_key_status_label, LV_SIZE_CONTENT);
lv_obj_set_align(ui_api_key_status_label, LV_ALIGN_LEFT_MID);
lv_label_set_text(ui_api_key_status_label, "API Key");

// 添加API Key状态指示器（右侧）
lv_obj_t *api_key_status_indicator = lv_label_create(api_key_status_panel);
lv_obj_set_width(api_key_status_indicator, LV_SIZE_CONTENT);
lv_obj_set_height(api_key_status_indicator, LV_SIZE_CONTENT);
lv_obj_set_align(api_key_status_indicator, LV_ALIGN_RIGHT_MID);
lv_label_set_text(api_key_status_indicator, "Not Set");
lv_obj_set_style_text_color(api_key_status_indicator, lv_color_hex(0xFF5555), LV_PART_MAIN | LV_STATE_DEFAULT);

// 创建API URL状态容器
lv_obj_t *api_url_status_panel = lv_obj_create(scroll_container);
ui_api_url_status_panel = api_url_status_panel;
lv_obj_set_width(api_url_status_panel, 400);
lv_obj_set_height(api_url_status_panel, 50);
lv_obj_set_x(api_url_status_panel, 0);
lv_obj_set_y(api_url_status_panel, 175);  // 与上一个面板保持6像素间距
lv_obj_set_align(api_url_status_panel, LV_ALIGN_CENTER);
lv_obj_clear_flag(api_url_status_panel, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_bg_color(api_url_status_panel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(api_url_status_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(api_url_status_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(api_url_status_panel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_all(api_url_status_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_y(api_url_status_panel, 280); // 上一个面板底部位置(224+50) + 间距(6)
lv_obj_set_align(api_url_status_panel, LV_ALIGN_TOP_MID);

// 添加API URL状态标签
ui_api_url_status_label = lv_label_create(api_url_status_panel);
lv_obj_set_width(ui_api_url_status_label, LV_SIZE_CONTENT);
lv_obj_set_height(ui_api_url_status_label, LV_SIZE_CONTENT);
lv_obj_set_align(ui_api_url_status_label, LV_ALIGN_LEFT_MID);
lv_label_set_text(ui_api_url_status_label, "API URL");

// 添加API URL状态指示器（右侧）
lv_obj_t *api_url_status_indicator = lv_label_create(api_url_status_panel);
lv_obj_set_width(api_url_status_indicator, LV_SIZE_CONTENT);
lv_obj_set_height(api_url_status_indicator, LV_SIZE_CONTENT);
lv_obj_set_align(api_url_status_indicator, LV_ALIGN_RIGHT_MID);
lv_label_set_text(api_url_status_indicator, "Not Set");
lv_obj_set_style_text_color(api_url_status_indicator, lv_color_hex(0xFF5555), LV_PART_MAIN | LV_STATE_DEFAULT);

// 创建Model Name状态容器
lv_obj_t *model_name_status_panel = lv_obj_create(scroll_container);
ui_model_name_status_panel = model_name_status_panel;
lv_obj_set_width(model_name_status_panel, 400);
lv_obj_set_height(model_name_status_panel, 50);
lv_obj_set_x(model_name_status_panel, 0);
lv_obj_set_y(model_name_status_panel, 231);  // 与上一个面板保持6像素间距
lv_obj_set_align(model_name_status_panel, LV_ALIGN_CENTER);
lv_obj_clear_flag(model_name_status_panel, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_bg_color(model_name_status_panel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(model_name_status_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(model_name_status_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(model_name_status_panel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_all(model_name_status_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_y(model_name_status_panel, 336); // 上一个面板底部位置(280+50) + 间距(6)
lv_obj_set_align(model_name_status_panel, LV_ALIGN_TOP_MID);

// 添加Model Name状态标签
ui_model_name_status_label = lv_label_create(model_name_status_panel);
lv_obj_set_width(ui_model_name_status_label, LV_SIZE_CONTENT);
lv_obj_set_height(ui_model_name_status_label, LV_SIZE_CONTENT);
lv_obj_set_align(ui_model_name_status_label, LV_ALIGN_LEFT_MID);
lv_label_set_text(ui_model_name_status_label, "Model Name");

// 添加Model Name状态指示器（右侧）
lv_obj_t *model_name_status_indicator = lv_label_create(model_name_status_panel);
lv_obj_set_width(model_name_status_indicator, LV_SIZE_CONTENT);
lv_obj_set_height(model_name_status_indicator, LV_SIZE_CONTENT);
lv_obj_set_align(model_name_status_indicator, LV_ALIGN_RIGHT_MID);
lv_label_set_text(model_name_status_indicator, "Default");
lv_obj_set_style_text_color(model_name_status_indicator, lv_color_hex(0x55FF55), LV_PART_MAIN | LV_STATE_DEFAULT);

// 修改滚动容器的内容高度设置
// 设置滚动容器的内容高度，确保可以滚动到最后一个面板
lv_obj_set_height(scroll_container, 350); // 设置固定高度
lv_obj_update_layout(scroll_container); // 更新布局

// 计算内容总高度 = 最后一个面板底部位置 + 面板高度 + 底部间距
int content_height = 336 + 50 + 25; // 最后一个面板y坐标 + 面板高度 + 底部间距
lv_obj_set_content_height(scroll_container, content_height);

// 确保滚动容器可滚动
lv_obj_set_scrollbar_mode(scroll_container, LV_SCROLLBAR_MODE_AUTO); // 自动显示滚动条

}

// 修改温度滑块事件回调函数
void ui_event_temperature_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    // 对所有事件类型都更新显示值
    int16_t value = lv_slider_get_value(target);
    g_temp_value = value / 10.0f;  // 将0-20的整数值转换为0-2.0的浮点数
    
    // 直接使用lv_label_set_text_fmt函数更新标签
    lv_label_set_text_fmt(ui_temperature_value, "%.1f", g_temp_value);

    // 输出当前滑条值到日志
    //ESP_LOGI("Temperature", "Current temperature value: %.1f", temp_value);
}

// 添加Max tokens滑块事件回调函数
void ui_event_max_tokens_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    g_max_tokens = lv_slider_get_value(target);
    
    // 更新显示值
    lv_label_set_text_fmt(ui_max_tokens_value, "%d", g_max_tokens);
    
}

// 修改温度开关事件回调函数
void ui_event_temperature_switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        // 保留回调函数但移除显示/隐藏逻辑
        // 可以在这里添加其他功能，如记录开关状态等
        ESP_LOGI(TAG, "Temperature switch state changed: %s", 
                 lv_obj_has_state(target, LV_STATE_CHECKED) ? "ON" : "OFF");
    }
}

// 修改Max tokens开关事件回调函数
void ui_event_max_tokens_switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        // 保留回调函数但移除显示/隐藏逻辑
        // 可以在这里添加其他功能，如记录开关状态等
        ESP_LOGI(TAG, "Max tokens switch state changed: %s", 
                 lv_obj_has_state(target, LV_STATE_CHECKED) ? "ON" : "OFF");
    }
}

void ui_update_api_status(bool have_key, bool have_url, bool have_model) {
    // 获取各个状态指示器
    lv_obj_t *api_key_indicator = lv_obj_get_child(ui_api_key_status_panel, 1);
    lv_obj_t *api_url_indicator = lv_obj_get_child(ui_api_url_status_panel, 1);
    lv_obj_t *model_name_indicator = lv_obj_get_child(ui_model_name_status_panel, 1);
    
    // 更新API Key状态
    if (have_key) {
        lv_label_set_text(api_key_indicator, "Set");
        lv_obj_set_style_text_color(api_key_indicator, lv_color_hex(0x55FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
        lv_label_set_text(api_key_indicator, "Not Set");
        lv_obj_set_style_text_color(api_key_indicator, lv_color_hex(0xFF5555), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    
    // 更新API URL状态
    if (have_url) {
        lv_label_set_text(api_url_indicator, "Set");
        lv_obj_set_style_text_color(api_url_indicator, lv_color_hex(0x55FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
        lv_label_set_text(api_url_indicator, "Not Set");
        lv_obj_set_style_text_color(api_url_indicator, lv_color_hex(0xFF5555), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    
    // 更新Model Name状态
    if (have_model) {
        lv_label_set_text(model_name_indicator, "Custom");
        lv_obj_set_style_text_color(model_name_indicator, lv_color_hex(0x55FF55), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
        lv_label_set_text(model_name_indicator, "Default");
        lv_obj_set_style_text_color(model_name_indicator, lv_color_hex(0x55AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
