// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"

void ui_screen_chartgpt_2_screen_init(void)
{
ui_screen_chartgpt_2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_chartgpt_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_chartgpt_2, lv_color_hex(0x343541), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_chartgpt_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_regennerate_btn = lv_btn_create(ui_screen_chartgpt_2);
lv_obj_set_width( ui_regennerate_btn, 215);
lv_obj_set_height( ui_regennerate_btn, 42);
lv_obj_set_x( ui_regennerate_btn, 165 );
lv_obj_set_y( ui_regennerate_btn, 406 );
lv_obj_add_flag( ui_regennerate_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_regennerate_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_regennerate_btn, lv_color_hex(0x10A37F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_regennerate_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_regennerate_title = lv_label_create(ui_regennerate_btn);
lv_obj_set_width( ui_regennerate_title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_regennerate_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_regennerate_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_regennerate_title,"Regenerate");
lv_obj_set_style_text_font(ui_regennerate_title, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_chatgpt2_back_btn = lv_btn_create(ui_screen_chartgpt_2);
lv_obj_set_width( ui_chatgpt2_back_btn, 100);
lv_obj_set_height( ui_chatgpt2_back_btn, 50);
lv_obj_set_x( ui_chatgpt2_back_btn, 10 );
lv_obj_set_y( ui_chatgpt2_back_btn, 30 );
lv_obj_add_flag( ui_chatgpt2_back_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_chatgpt2_back_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_chatgpt2_back_btn, lv_color_hex(0x343541), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_chatgpt2_back_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_chatgpt2_back_btn, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_chatgpt_title = lv_label_create(ui_screen_chartgpt_2);
lv_obj_set_width( ui_chatgpt_title, LV_SIZE_CONTENT);  /// 208
lv_obj_set_height( ui_chatgpt_title, LV_SIZE_CONTENT);   /// 33
lv_obj_set_x( ui_chatgpt_title, 0 );
lv_obj_set_y( ui_chatgpt_title, -183 );
lv_obj_set_align( ui_chatgpt_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_chatgpt_title,"ChatGPT");
lv_obj_set_style_text_font(ui_chatgpt_title, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logo_request = lv_img_create(ui_screen_chartgpt_2); 
lv_img_set_src(ui_logo_request, &ui_img_sensecap_log_png);
lv_obj_set_width( ui_logo_request, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_logo_request, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_logo_request, 30 );
lv_obj_set_y( ui_logo_request, 107 );
lv_obj_add_flag( ui_logo_request, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_logo_request, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_text_readonly_gpt_request = lv_label_create(ui_screen_chartgpt_2);
lv_obj_set_width( ui_text_readonly_gpt_request, 364);
lv_obj_set_height( ui_text_readonly_gpt_request, 59);
lv_obj_set_x( ui_text_readonly_gpt_request, 92 );
lv_obj_set_y( ui_text_readonly_gpt_request, 100 );
lv_obj_set_style_radius(ui_text_readonly_gpt_request, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_textarea_set_max_length(ui_text_readonly_gpt_request,200);
lv_obj_set_style_bg_color(ui_text_readonly_gpt_request, lv_color_hex(0x5C5E6D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_text_readonly_gpt_request, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_text_readonly_gpt_request, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_text_readonly_gpt_request, LV_TEXT_ALIGN_LEFT, 0);
lv_obj_set_style_pad_all(ui_text_readonly_gpt_request, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_text_readonly_gpt_request,8,0);

ui_text_readonly_gpt_response = lv_textarea_create(ui_screen_chartgpt_2);
lv_obj_set_width( ui_text_readonly_gpt_response, 364);
lv_obj_set_height( ui_text_readonly_gpt_response, 204);
lv_obj_set_x( ui_text_readonly_gpt_response, 91 );
lv_obj_set_y( ui_text_readonly_gpt_response, 172 );
lv_textarea_set_max_length(ui_text_readonly_gpt_response,1024);
lv_obj_set_style_bg_color(ui_text_readonly_gpt_response, lv_color_hex(0x5C5E6D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_text_readonly_gpt_response, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_text_readonly_gpt_response, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_add_flag( ui_text_readonly_gpt_response, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_pad_all(ui_text_readonly_gpt_response, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_text_readonly_gpt_response,8,0);

ui_logo_response = lv_img_create(ui_screen_chartgpt_2); 
lv_img_set_src(ui_logo_response, &ui_img_chatgpt_log_png);
lv_obj_set_width( ui_logo_response, LV_SIZE_CONTENT);  /// 49
lv_obj_set_height( ui_logo_response, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_logo_response, 30 );
lv_obj_set_y( ui_logo_response, 176 );
lv_obj_add_flag( ui_logo_response, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_logo_response, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_wifi_st_10 = lv_img_create(ui_screen_chartgpt_2);
lv_img_set_src(ui_wifi_st_10, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_st_10, -20 );
lv_obj_set_y( ui_wifi_st_10, 20 );
lv_obj_set_align( ui_wifi_st_10, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
