// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ASIS

#include "./ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_screen_ha_data
void ui_screen_ha_data_screen_init(void);
lv_obj_t *ui_screen_ha_data;
lv_obj_t *ui_ha_data_wifi_st;
lv_obj_t *ui_ha_data_time;
lv_obj_t *ui_screen_home_data_label;
lv_obj_t *ui_sensor1_btn;
lv_obj_t *ui_sensor1_logo;
lv_obj_t *ui_sensor1_label;
lv_obj_t *ui_sensor1_data;
lv_obj_t *ui_sensor1_unit;
lv_obj_t *ui_sensor2_btn;
lv_obj_t *ui_sensor2_logo;
lv_obj_t *ui_sensor2_label;
lv_obj_t *ui_sensor2_data;
lv_obj_t *ui_sensor2_unit;
lv_obj_t *ui_sensor3_btn;
lv_obj_t *ui_sensor3_logo;
lv_obj_t *ui_sensor3_label;
lv_obj_t *ui_sensor3_data;
lv_obj_t *ui_sensor3_unit;
lv_obj_t *ui_sensor4_btn;
lv_obj_t *ui_sensor4_logo;
lv_obj_t *ui_sensor4_label;
lv_obj_t *ui_sensor4_data;
lv_obj_t *ui_sensor4_unit;

// SCREEN: ui_screen_ha
void ui_screen_ha_screen_init(void);
lv_obj_t *ui_screen_ha;
lv_obj_t *ui_ha_wifi_st;
lv_obj_t *ui_ha_time;
lv_obj_t *ui_screen_home_none_lable;
lv_obj_t *ui_sensor5_btn;
lv_obj_t *ui_sensor5_logo;
lv_obj_t *ui_sensor5_label;
lv_obj_t *ui_sensor5_data;
lv_obj_t *ui_sensor5_unit;
lv_obj_t *ui_sensor6_btn;
lv_obj_t *ui_sensor6_logo;
lv_obj_t *ui_sensor6_label;
lv_obj_t *ui_sensor6_data;
lv_obj_t *ui_sensor6_unit;
lv_obj_t *ui_switch1;
lv_obj_t *ui_switch1_logo;
lv_obj_t *ui_switch1_label;
lv_obj_t *ui_switch2;
lv_obj_t *ui_switch2_logo;
lv_obj_t *ui_switch2_label;
lv_obj_t *ui_switch3;
lv_obj_t *ui_switch3_label;
lv_obj_t *ui_switch3_switch;

// SCREEN: ui_screen_ha_ctrl
void ui_screen_ha_ctrl_screen_init(void);
lv_obj_t *ui_screen_ha_ctrl;
lv_obj_t *ui_ha_ctrl_wifi_st;
lv_obj_t *ui_ha_ctrl_time;
lv_obj_t *ui_screen_home_ctrl_lable;
lv_obj_t *ui_switch4;
lv_obj_t *ui_switch4_logo;
lv_obj_t *ui_switch4_label;
lv_obj_t *ui_switch5;
lv_obj_t *ui_switch5_arc;
lv_obj_t *ui_switch5_arc_data;
lv_obj_t *ui_switch5_label;
lv_obj_t *ui_switch6;
lv_obj_t *ui_switch6_logo;
lv_obj_t *ui_switch6_label;
lv_obj_t *ui_switch7;
lv_obj_t *ui_switch7_label;
lv_obj_t *ui_switch7_switch;
lv_obj_t *ui_switch8;
lv_obj_t *ui_switch8_label;
lv_obj_t *ui_switch8_slider;



///////////////////// SCREENS ////////////////////
void ui_ha_init( void )
{
    ui_screen_ha_data_screen_init();
    ui_screen_ha_screen_init();
    ui_screen_ha_ctrl_screen_init();
}
