// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ASIS

#ifndef _ASIS_UI_H
#define _ASIS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ha_config.h"

// SCREEN: ui_screen_ha_data
void ui_screen_ha_data_screen_init(void);
extern lv_obj_t *ui_screen_ha_data;
extern lv_obj_t *ui_ha_data_wifi_btn;
extern lv_obj_t *ui_ha_data_wifi_st;
extern lv_obj_t *ui_ha_data_time;
extern lv_obj_t *ui_screen_home_data_label;
extern lv_obj_t *ui_sensor1_btn;
extern lv_obj_t *ui_sensor1_logo;
extern lv_obj_t *ui_sensor1_label;
extern lv_obj_t *ui_sensor1_data;
extern lv_obj_t *ui_sensor1_unit;
extern lv_obj_t *ui_sensor2_btn;
extern lv_obj_t *ui_sensor2_logo;
extern lv_obj_t *ui_sensor2_label;
extern lv_obj_t *ui_sensor2_data;
extern lv_obj_t *ui_sensor2_unit;
extern lv_obj_t *ui_sensor3_btn;
extern lv_obj_t *ui_sensor3_logo;
extern lv_obj_t *ui_sensor3_label;
extern lv_obj_t *ui_sensor3_data;
extern lv_obj_t *ui_sensor3_unit;
extern lv_obj_t *ui_sensor4_btn;
extern lv_obj_t *ui_sensor4_logo;
extern lv_obj_t *ui_sensor4_label;
extern lv_obj_t *ui_sensor4_data;
extern lv_obj_t *ui_sensor4_unit;
// SCREEN: ui_screen_ha
void ui_screen_ha_screen_init(void);
extern lv_obj_t *ui_screen_ha;
extern lv_obj_t *ui_ha_wifi_btn;
extern lv_obj_t *ui_ha_wifi_st;
extern lv_obj_t *ui_ha_time;
extern lv_obj_t *ui_screen_home_none_lable;
extern lv_obj_t *ui_sensor5_btn;
extern lv_obj_t *ui_sensor5_logo;
extern lv_obj_t *ui_sensor5_label;
extern lv_obj_t *ui_sensor5_data;
extern lv_obj_t *ui_sensor5_unit;
extern lv_obj_t *ui_sensor6_btn;
extern lv_obj_t *ui_sensor6_logo;
extern lv_obj_t *ui_sensor6_label;
extern lv_obj_t *ui_sensor6_data;
extern lv_obj_t *ui_sensor6_unit;
extern lv_obj_t *ui_switch1;
extern lv_obj_t *ui_switch1_logo;
extern lv_obj_t *ui_switch1_label;
extern lv_obj_t *ui_switch2;
extern lv_obj_t *ui_switch2_logo;
extern lv_obj_t *ui_switch2_label;
extern lv_obj_t *ui_switch3;
extern lv_obj_t *ui_switch3_label;
extern lv_obj_t *ui_switch3_switch;
// SCREEN: ui_screen_ha_ctrl
void ui_screen_ha_ctrl_screen_init(void);
extern lv_obj_t *ui_screen_ha_ctrl;
extern lv_obj_t *ui_ha_ctrl_wifi_btn;
extern lv_obj_t *ui_ha_ctrl_wifi_st;
extern lv_obj_t *ui_ha_ctrl_time;
extern lv_obj_t *ui_screen_home_ctrl_lable;
extern lv_obj_t *ui_switch4;
extern lv_obj_t *ui_switch4_logo;
extern lv_obj_t *ui_switch4_label;
extern lv_obj_t *ui_switch5;
extern lv_obj_t *ui_switch5_arc;
extern lv_obj_t *ui_switch5_arc_data;
extern lv_obj_t *ui_switch5_label;
extern lv_obj_t *ui_switch6;
extern lv_obj_t *ui_switch6_logo;
extern lv_obj_t *ui_switch6_label;
extern lv_obj_t *ui_switch7;
extern lv_obj_t *ui_switch7_label;
extern lv_obj_t *ui_switch7_switch;
extern lv_obj_t *ui_switch8;
extern lv_obj_t *ui_switch8_label;
extern lv_obj_t *ui_switch8_slider;

LV_IMG_DECLARE( ui_img_ic_temp_png);   // assets/ic_temp.png
LV_IMG_DECLARE( ui_img_ic_hum_png);   // assets/ic_hum.png
LV_IMG_DECLARE( ui_img_ic_tvoc_png);   // assets/ic_tVOC.png
LV_IMG_DECLARE( ui_img_ic_co2_png);   // assets/ic_co2.png
LV_IMG_DECLARE( ui_img_ic_switch2_on_png);   // assets/ic_switch2_on.png
LV_IMG_DECLARE( ui_img_ic_switch1_on_png);   // assets/ic_switch1_on.png
LV_IMG_DECLARE( ui_img_ic_switch2_off_png);   // assets/ic_switch2_off.png
LV_IMG_DECLARE( ui_img_ic_switch1_off_png);   // assets/ic_switch1_off.png



void ui_ha_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
