// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorahub

#include "../ui.h"

void ui_comp_BtnWifi1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_date_time1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ImgBackground_create_hook(lv_obj_t * comp)
{
}
