// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorahub

#include "../ui.h"


// COMPONENT BtnWifi1

lv_obj_t * ui_BtnWifi1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BtnWifi1;
    cui_BtnWifi1 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_BtnWifi1, 60);
    lv_obj_set_height(cui_BtnWifi1, 60);
    lv_obj_set_x(cui_BtnWifi1, -10);
    lv_obj_set_y(cui_BtnWifi1, 10);
    lv_obj_set_align(cui_BtnWifi1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(cui_BtnWifi1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_BtnWifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_BtnWifi1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BtnWifi1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblWifiStatus1;
    cui_LblWifiStatus1 = lv_img_create(cui_BtnWifi1);
    lv_img_set_src(cui_LblWifiStatus1, &ui_img_wifi_disconet_png);
    lv_obj_set_width(cui_LblWifiStatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblWifiStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LblWifiStatus1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(cui_LblWifiStatus1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_LblWifiStatus1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTNWIFI1_NUM);
    children[UI_COMP_BTNWIFI1_BTNWIFI1] = cui_BtnWifi1;
    children[UI_COMP_BTNWIFI1_LBLWIFISTATUS1] = cui_LblWifiStatus1;
    lv_obj_add_event_cb(cui_BtnWifi1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BtnWifi1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BtnWifi1_create_hook(cui_BtnWifi1);
    return cui_BtnWifi1;
}

