// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorahub

#ifndef _UI_COMP_BTNWIFI1_H
#define _UI_COMP_BTNWIFI1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BtnWifi1
#define UI_COMP_BTNWIFI1_BTNWIFI1 0
#define UI_COMP_BTNWIFI1_LBLWIFISTATUS1 1
#define _UI_COMP_BTNWIFI1_NUM 2
lv_obj_t * ui_BtnWifi1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
