// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorahub

#include "../ui.h"


// COMPONENT ImgBackground

lv_obj_t * ui_ImgBackground_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ImgBackground;
    cui_ImgBackground = lv_img_create(comp_parent);
    lv_img_set_src(cui_ImgBackground, &ui_img_background_png);
    lv_obj_set_width(cui_ImgBackground, lv_pct(100));
    lv_obj_set_height(cui_ImgBackground, lv_pct(100));
    lv_obj_set_align(cui_ImgBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ImgBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_ImgBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_PnlHour;
    cui_PnlHour = lv_obj_create(cui_ImgBackground);
    lv_obj_set_width(cui_PnlHour, 200);
    lv_obj_set_height(cui_PnlHour, 170);
    lv_obj_set_x(cui_PnlHour, -110);
    lv_obj_set_y(cui_PnlHour, 0);
    lv_obj_set_align(cui_PnlHour, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PnlHour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_PnlHour, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_PnlHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblHour;
    cui_LblHour = lv_label_create(cui_PnlHour);
    lv_obj_set_width(cui_LblHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LblHour, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblHour, "20");
    lv_obj_set_style_text_font(cui_LblHour, &ui_font_OnlyNumBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_PnlMin;
    cui_PnlMin = lv_obj_create(cui_ImgBackground);
    lv_obj_set_width(cui_PnlMin, 200);
    lv_obj_set_height(cui_PnlMin, 170);
    lv_obj_set_x(cui_PnlMin, 110);
    lv_obj_set_y(cui_PnlMin, 0);
    lv_obj_set_align(cui_PnlMin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PnlMin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_PnlMin, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_PnlMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblMin;
    cui_LblMin = lv_label_create(cui_PnlMin);
    lv_obj_set_width(cui_LblMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LblMin, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblMin, "23");
    lv_obj_set_style_text_font(cui_LblMin, &ui_font_OnlyNumBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Pnllocation;
    cui_Pnllocation = lv_obj_create(cui_ImgBackground);
    lv_obj_set_width(cui_Pnllocation, 399);
    lv_obj_set_height(cui_Pnllocation, 30);
    lv_obj_set_x(cui_Pnllocation, 6);
    lv_obj_set_y(cui_Pnllocation, 103);
    lv_obj_set_align(cui_Pnllocation, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Pnllocation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Pnllocation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Pnllocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Pnllocation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Pnllocation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Pnllocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblCity;
    cui_LblCity = lv_label_create(cui_Pnllocation);
    lv_obj_set_width(cui_LblCity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblCity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LblCity, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_LblCity, "Shen Zhen");
    lv_obj_set_style_text_font(cui_LblCity, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ImgLocation;
    cui_ImgLocation = lv_img_create(cui_ImgBackground);
    lv_img_set_src(cui_ImgLocation, &ui_img_location2_png);
    lv_obj_set_width(cui_ImgLocation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_ImgLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ImgLocation, 199);
    lv_obj_set_y(cui_ImgLocation, 103);
    lv_obj_set_align(cui_ImgLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ImgLocation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_ImgLocation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_PnlDate;
    cui_PnlDate = lv_obj_create(cui_ImgBackground);
    lv_obj_set_width(cui_PnlDate, 235);
    lv_obj_set_height(cui_PnlDate, 30);
    lv_obj_set_x(cui_PnlDate, -103);
    lv_obj_set_y(cui_PnlDate, -108);
    lv_obj_set_align(cui_PnlDate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PnlDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_PnlDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_PnlDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_PnlDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_PnlDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_PnlDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblDate;
    cui_LblDate = lv_label_create(cui_PnlDate);
    lv_obj_set_width(cui_LblDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LblDate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_LblDate, "Monday, 06 / 03 /  2023");
    lv_label_set_recolor(cui_LblDate, "true");
    lv_obj_set_style_text_font(cui_LblDate, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblDotTime;
    cui_LblDotTime = lv_label_create(cui_ImgBackground);
    lv_obj_set_width(cui_LblDotTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblDotTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LblDotTime, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblDotTime, ":");
    lv_obj_set_style_text_font(cui_LblDotTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_PnlSlide;
    cui_PnlSlide = lv_obj_create(cui_ImgBackground);
    lv_obj_set_width(cui_PnlSlide, 480);
    lv_obj_set_height(cui_PnlSlide, 6);
    lv_obj_set_align(cui_PnlSlide, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PnlSlide, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_PnlSlide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_PnlSlide, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_PnlSlide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_PnlSlide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_PnlSlide, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IMGBACKGROUND_NUM);
    children[UI_COMP_IMGBACKGROUND_IMGBACKGROUND] = cui_ImgBackground;
    children[UI_COMP_IMGBACKGROUND_PNLHOUR] = cui_PnlHour;
    children[UI_COMP_IMGBACKGROUND_PNLHOUR_LBLHOUR] = cui_LblHour;
    children[UI_COMP_IMGBACKGROUND_PNLMIN] = cui_PnlMin;
    children[UI_COMP_IMGBACKGROUND_PNLMIN_LBLMIN] = cui_LblMin;
    children[UI_COMP_IMGBACKGROUND_PNLLOCATION] = cui_Pnllocation;
    children[UI_COMP_IMGBACKGROUND_PNLLOCATION_LBLCITY] = cui_LblCity;
    children[UI_COMP_IMGBACKGROUND_IMGLOCATION] = cui_ImgLocation;
    children[UI_COMP_IMGBACKGROUND_PNLDATE] = cui_PnlDate;
    children[UI_COMP_IMGBACKGROUND_PNLDATE_LBLDATE] = cui_LblDate;
    children[UI_COMP_IMGBACKGROUND_LBLDOTTIME] = cui_LblDotTime;
    children[UI_COMP_IMGBACKGROUND_PNLSLIDE] = cui_PnlSlide;
    lv_obj_add_event_cb(cui_ImgBackground, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ImgBackground, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ImgBackground_create_hook(cui_ImgBackground);
    return cui_ImgBackground;
}

