// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: indicator_lorahub

#ifndef _UI_COMP_IMGBACKGROUND_H
#define _UI_COMP_IMGBACKGROUND_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ImgBackground
#define UI_COMP_IMGBACKGROUND_IMGBACKGROUND 0
#define UI_COMP_IMGBACKGROUND_PNLHOUR 1
#define UI_COMP_IMGBACKGROUND_PNLHOUR_LBLHOUR 2
#define UI_COMP_IMGBACKGROUND_PNLMIN 3
#define UI_COMP_IMGBACKGROUND_PNLMIN_LBLMIN 4
#define UI_COMP_IMGBACKGROUND_PNLLOCATION 5
#define UI_COMP_IMGBACKGROUND_PNLLOCATION_LBLCITY 6
#define UI_COMP_IMGBACKGROUND_IMGLOCATION 7
#define UI_COMP_IMGBACKGROUND_PNLDATE 8
#define UI_COMP_IMGBACKGROUND_PNLDATE_LBLDATE 9
#define UI_COMP_IMGBACKGROUND_LBLDOTTIME 10
#define UI_COMP_IMGBACKGROUND_PNLSLIDE 11
#define _UI_COMP_IMGBACKGROUND_NUM 12
lv_obj_t * ui_ImgBackground_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
