// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"

void ui_screen_dalle_1_screen_init(void)
{
ui_screen_dalle_1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_dalle_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dalle_back_btn = lv_btn_create(ui_screen_dalle_1);
lv_obj_set_width( ui_dalle_back_btn, 100);
lv_obj_set_height( ui_dalle_back_btn, 50);
lv_obj_set_x( ui_dalle_back_btn, 10 );
lv_obj_set_y( ui_dalle_back_btn, 30 );
lv_obj_add_flag( ui_dalle_back_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_dalle_back_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_dalle_back_btn, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dalle_back_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_dalle_back_btn, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_btn_dall_supriseme = lv_btn_create(ui_screen_dalle_1);
lv_obj_set_width( ui_btn_dall_supriseme, 206);
lv_obj_set_height( ui_btn_dall_supriseme, 42);
lv_obj_set_x( ui_btn_dall_supriseme, 137 );
lv_obj_set_y( ui_btn_dall_supriseme, 406 );
lv_obj_add_flag( ui_btn_dall_supriseme, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btn_dall_supriseme, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btn_dall_supriseme, lv_color_hex(0x10A37F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btn_dall_supriseme, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_btn_dall_supriseme);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Suprise Me");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dalle_title1 = lv_label_create(ui_screen_dalle_1);
lv_obj_set_width( ui_dalle_title1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dalle_title1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dalle_title1, 0 );
lv_obj_set_y( ui_dalle_title1, -180 );
lv_obj_set_align( ui_dalle_title1, LV_ALIGN_CENTER );
lv_label_set_text(ui_dalle_title1,"DALL•E");
lv_obj_set_style_text_align(ui_dalle_title1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_dalle_title1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dalle_title1, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dalle_text = lv_textarea_create(ui_screen_dalle_1);
lv_obj_set_width( ui_dalle_text, 434);
lv_obj_set_height( ui_dalle_text, 288);
lv_obj_set_x( ui_dalle_text, 2 );
lv_obj_set_y( ui_dalle_text, -2 );
lv_obj_set_align( ui_dalle_text, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_dalle_text,2000);
lv_textarea_set_placeholder_text(ui_dalle_text,"Astronaut riding a horse in space.");
lv_obj_set_style_text_color(ui_dalle_text, lv_color_hex(0x0E0E0E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dalle_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_dalle_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dalle_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard_dalle = lv_keyboard_create(ui_screen_dalle_1);
lv_obj_set_width( ui_Keyboard_dalle, 480);
lv_obj_set_height( ui_Keyboard_dalle, 220);
lv_obj_set_x( ui_Keyboard_dalle, 0 );
lv_obj_set_y( ui_Keyboard_dalle, 136 );
lv_obj_set_align( ui_Keyboard_dalle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard_dalle, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_wifi_st_11 = lv_img_create(ui_screen_dalle_1);
lv_img_set_src(ui_wifi_st_11, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_st_11, -20 );
lv_obj_set_y( ui_wifi_st_11, 20 );
lv_obj_set_align( ui_wifi_st_11, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


}
