// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"

void ui_screen_dalle_2_screen_init(void)
{
ui_screen_dalle_2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_dalle_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btn_dall2_regenerate = lv_btn_create(ui_screen_dalle_2);
lv_obj_set_width( ui_btn_dall2_regenerate, 206);
lv_obj_set_height( ui_btn_dall2_regenerate, 42);
lv_obj_set_x( ui_btn_dall2_regenerate, 137 );
lv_obj_set_y( ui_btn_dall2_regenerate, 406 );
lv_obj_add_flag( ui_btn_dall2_regenerate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btn_dall2_regenerate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btn_dall2_regenerate, lv_color_hex(0x10A37F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btn_dall2_regenerate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btn_dall2_regenerate_title = lv_label_create(ui_btn_dall2_regenerate);
lv_obj_set_width( ui_btn_dall2_regenerate_title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_btn_dall2_regenerate_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_btn_dall2_regenerate_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_btn_dall2_regenerate_title,"Regenerate");
lv_obj_set_style_text_font(ui_btn_dall2_regenerate_title, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dalle2_back_btn = lv_btn_create(ui_screen_dalle_2);
lv_obj_set_width( ui_dalle2_back_btn, 100);
lv_obj_set_height( ui_dalle2_back_btn, 50);
lv_obj_set_x( ui_dalle2_back_btn, 10 );
lv_obj_set_y( ui_dalle2_back_btn, 30 );
lv_obj_add_flag( ui_dalle2_back_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_dalle2_back_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_dalle2_back_btn, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dalle2_back_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_dalle2_back_btn, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Label11 = lv_label_create(ui_screen_dalle_2);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 0 );
lv_obj_set_y( ui_Label11, -180 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"DALL•E");
lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label11, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dall_image = lv_img_create(ui_screen_dalle_2);
lv_obj_set_width( ui_dall_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dall_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dall_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dall_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_dall_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_dall_image, 128);
lv_obj_add_flag( ui_dall_image, LV_OBJ_FLAG_CLICKABLE );  

ui_wifi_st_12 = lv_img_create(ui_screen_dalle_2);
lv_img_set_src(ui_wifi_st_12, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_st_12, -20 );
lv_obj_set_y( ui_wifi_st_12, 20 );
lv_obj_set_align( ui_wifi_st_12, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
