// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"

void ui_screen_openai_key_screen_init(void)
{
ui_screen_openai_key = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_openai_key, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi_st_8 = lv_img_create(ui_screen_openai_key);
lv_img_set_src(ui_wifi_st_8, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_st_8, -20 );
lv_obj_set_y( ui_wifi_st_8, 20 );
lv_obj_set_align( ui_wifi_st_8, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_set_api_key_title1 = lv_label_create(ui_screen_openai_key);
lv_obj_set_width( ui_set_api_key_title1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_set_api_key_title1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_set_api_key_title1, 1 );
lv_obj_set_y( ui_set_api_key_title1, 50 );
lv_obj_set_align( ui_set_api_key_title1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_set_api_key_title1,"Set API Key");
lv_obj_set_style_text_font(ui_set_api_key_title1, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_api_key_back_btn = lv_btn_create(ui_screen_openai_key);
lv_obj_set_width( ui_api_key_back_btn, 100);
lv_obj_set_height( ui_api_key_back_btn, 50);
lv_obj_set_x( ui_api_key_back_btn, 10 );
lv_obj_set_y( ui_api_key_back_btn, 30 );
lv_obj_add_flag( ui_api_key_back_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_api_key_back_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_api_key_back_btn, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_api_key_back_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_api_key_back_btn, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_qr_code = lv_img_create(ui_screen_openai_key);
lv_img_set_src(ui_qr_code, &ui_img_set_key_qr_code_png);
lv_obj_set_width( ui_qr_code, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_qr_code, LV_SIZE_CONTENT);   /// 200
lv_obj_set_align( ui_qr_code, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_qr_code, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qr_code, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
