// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"

void ui_screen_chartgpt_1_screen_init(void)
{
ui_screen_chartgpt_1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_chartgpt_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_chartgpt_1, lv_color_hex(0x343541), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_chartgpt_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_chatgpt_1_title = lv_label_create(ui_screen_chartgpt_1);
lv_obj_set_width( ui_chatgpt_1_title, LV_SIZE_CONTENT);  /// 208
lv_obj_set_height( ui_chatgpt_1_title, LV_SIZE_CONTENT);   /// 33
lv_obj_set_x( ui_chatgpt_1_title, 0 );
lv_obj_set_y( ui_chatgpt_1_title, -183 );
lv_obj_set_align( ui_chatgpt_1_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_chatgpt_1_title,"ChatGPT");
lv_obj_set_style_text_font(ui_chatgpt_1_title, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_generate_answer_btn = lv_btn_create(ui_screen_chartgpt_1);
lv_obj_set_width( ui_generate_answer_btn, 206);
lv_obj_set_height( ui_generate_answer_btn, 42);
lv_obj_set_x( ui_generate_answer_btn, 137 );
lv_obj_set_y( ui_generate_answer_btn, 406 );
lv_obj_add_flag( ui_generate_answer_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_generate_answer_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_generate_answer_btn, lv_color_hex(0x10A37F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_generate_answer_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_generate_answer_title = lv_label_create(ui_generate_answer_btn);
lv_obj_set_width( ui_generate_answer_title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_generate_answer_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_generate_answer_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_generate_answer_title,"Generate Answer");
lv_obj_set_style_text_font(ui_generate_answer_title, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_chatgpt_back_btn = lv_btn_create(ui_screen_chartgpt_1);
lv_obj_set_width( ui_chatgpt_back_btn, 100);
lv_obj_set_height( ui_chatgpt_back_btn, 50);
lv_obj_set_x( ui_chatgpt_back_btn, 10 );
lv_obj_set_y( ui_chatgpt_back_btn, 30 );
lv_obj_add_flag( ui_chatgpt_back_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_chatgpt_back_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_chatgpt_back_btn, lv_color_hex(0x343541), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_chatgpt_back_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_chatgpt_back_btn, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );

/* add panel */
ui_Panel1 = lv_obj_create(ui_screen_chartgpt_1);
lv_obj_set_width(ui_Panel1, 434);
lv_obj_set_height(ui_Panel1, 288);
lv_obj_set_x(ui_Panel1, 24);
lv_obj_set_y(ui_Panel1, 89);
lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
lv_obj_set_style_radius(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x444654), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

ui_text_edit_gpt_request = lv_textarea_create(ui_Panel1);
lv_obj_set_width(ui_text_edit_gpt_request, 345);
lv_obj_set_height(ui_text_edit_gpt_request, 154);
lv_obj_set_x(ui_text_edit_gpt_request, 28);
lv_obj_set_y(ui_text_edit_gpt_request, 31);
lv_textarea_set_max_length(ui_text_edit_gpt_request,200);
lv_textarea_set_placeholder_text(ui_text_edit_gpt_request,"Enter your question here to get answer from ChatGPT...");
lv_obj_set_style_bg_color(ui_text_edit_gpt_request, lv_color_hex(0x444654), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_text_edit_gpt_request, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_text_edit_gpt_request, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_text_edit_gpt_request, lv_color_hex(0x343541), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_text_edit_gpt_request, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
/* END */

ui_Keyboard_chatgpt = lv_keyboard_create(ui_screen_chartgpt_1);
lv_obj_set_width( ui_Keyboard_chatgpt, 480);
lv_obj_set_height( ui_Keyboard_chatgpt, 220);
lv_obj_set_x( ui_Keyboard_chatgpt, 0 );
lv_obj_set_y( ui_Keyboard_chatgpt, 136 );
lv_obj_set_align( ui_Keyboard_chatgpt, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard_chatgpt, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_wifi_st_9 = lv_img_create(ui_screen_chartgpt_1);
lv_img_set_src(ui_wifi_st_9, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_st_9, -20 );
lv_obj_set_y( ui_wifi_st_9, 20 );
lv_obj_set_align( ui_wifi_st_9, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
