name: build SenseCAP Indicator ESP32-S3

on:
  push:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0
          
      - name: Patch ESP-IDF
        run: cd /tools/patch && chmod +x install_patch.sh && ./install_patch.sh

    
      - name: esp-idf build Home Assistant firmware
        run: cd '/examples/indicator_ha' && idf.py build
